src/Widgets/WindowMenu.vala

There is only one menu made that is shared across all windows. Setting `always_on_top.active` caused the `activate` (and `toggled` as well) signal to execute, causing the current window to get the results of the previous window. 
Fixes: #17

Fixed: Window menu applies previous settings to new window

---

plugins/pip/PopupWindow.vala
plugins/pip/ShadowEffect.vala

Fixes GObject registration of the `ShadowEffect` class. The class was having the same signature as it's original one in Gala itself and could not be registered as a valid class.

pip: Fix ShadowEffect namespace

---

data/org.pantheon.desktop.gala.gschema.xml.in

Change the shortcut to a more logical `Super+P`.

pip: Change the shortcut to Super+P

---

plugins/pip/PopupWindow.vala

Fixes #35.
This fixes an incorrect shadow size appearing for Gtk+3 windows by getting the right window frame instead of the entire window actor. To accompansate for the top and left edge, the clone is shifted to `x_offset` and `y_offset` and a new size is set for the clone container, since the clone now has a clip that is the actual size of the clone, rather than it's original window actor size.

pip: Fix Gtk+3 windows having an incorrect allocation size

---

plugins/pip/Main.vala

Fixes #76.
Fixes comparasion of the choosen point on the screen with window actors: instead of comparing the point to the entire actor, the branch comapres it to the real window frame rectangle. I've added a `meta_rectangle_contains` static function since there is no replacement for that in the `Meta.Rectangle` itself.

pip: Compare the chosen point coordinates against the real window frame

---

src/Widgets/WindowClone.vala

Fixes #19.
This fixes an issue with fading out minimized windows when closing the window overview as well as the multitasking view. In master when the window is minimized, it'll transition to it's original state but will not fade out meaning that it will reach it's original position and then disappear without any animation / fade out. The branch changes that so that minimized windows are faded out properly when exiting the window overview.

Fix minimized windows not fading out when closing window overview

---

src/Widgets/MultitaskingView.vala

Currently, scrolling during the closing animation changes the workspace, up to the last second of the animation. This makes you have to wait until the animation stops before you can start scrolling on a web page for example
Just added a check to see if it was opened, and returns if it's not :)

MultitaskingView: Don't allow scrolling though workspaces while closing

---

README.md

Running `autogen.sh` would result in
```
configure: error: xmllint not found
```
I understood from [pull request #36](https://github.com/elementary/gala/pull/36) that it was missing `libxml2-utils` as dependency

Document libxml2-utils as dependency

---

README.md

Because if you compile with the current command you will get errors and `pip` will not work :cry:

Update autogen command

---

src/ScreenshotManager.vala

A sub-branch of https://github.com/elementary/gala/pull/11, implements the `screenshot_area` DBus method in the `org.gnome.Shell.Screenshot` interface.

Implement screenshot_area

---

src/Makefile.am
src/ScreenshotManager.vala
src/Widgets/SelectionArea.vala

This branch implements `select_area` in `org.gnome.Shell.Screenshot` DBus interface. The SelectionArea.vala file is copied from PIP plugin and has been a little bit modified to fit the requirements of selecting an area of a screenshot.
I changed the signature of the `select_area` method has been changed to be async since we need to wait for the user to select the area and then return results.

Implement select_area

---

plugins/pip/Main.vala
plugins/pip/PopupWindow.vala

Fixes #99.
Hides the preview when the choosen window is currently focused.

pip: Hide the preview when the target window is focused

---

plugins/pip/PopupWindow.vala

Fixes #169.
Do not update PiP window visibility when switching from a non-normal window, that is docks, desktop windows etc. This prevents hiding the PiP window when e.g: showing a popover from wingpanel.

pip: only update focus changes when switching from a normal window

---

data/org.pantheon.desktop.gala.gschema.xml.in

Decreases window close duration from 300 to 195, which is a little bit faster, we discussed this in #56 and it seems that 195 is a good middleground for this setting.

gsettings: make window close duration shorter

---

src/WindowManager.vala

Prevents from cycling to a new workspace in dynamic mode when using Super+Tab and Super+Shift+Tab. Super+Arrows still work the same as before.

Do not cycle through the new workspace in dynamic workspaces

---

src/InternalUtils.vala
src/WindowManager.vala

Fixes #116.
When a window is fullscreened, shift all the workspaces and their windows by 1 to make space for a new workspace next to the workspace that the window was originally fullscreened on.
That means if you fullscreen a window on the first workspace, it'll go to new a second one and all other workspaces will be shifted to the right to make space for that second workspace.

Move the fullscreened window to the next workspace

---

src/WindowManager.vala

Fixes #75.
It looks like that some internal changes in mutter caused `get_frame_rect` to return not updated new size of the window resizing. (This is because for some reason the frame size is updated after the actual `size_change` method in the plugin is called: https://github.com/GNOME/mutter/blob/20176d0395294b9eeb7f0e28f1a1a35705fa0888/src/core/window.c#L2866)
That's why the animation happened, but there was no scale animation visible, only opacity. Waiting for the `size_changed` signal works here.

Fix maximize / minimize animations

---

src/WindowManager.vala

This fixes an issue where you could constantly move a window to the next workspace with `Super+Alt+Right`.
This was the case because gala wrongly assumed that `n_windows` returns only normal windows from the workspace while it returns the count of all windows (dock, panel etc.) so this always condition was always false.

Dont move window from last workspace to another

---

src/BlurActor.vala

Small change to fix blur background position when window is animating (scaling).

Fix background position for scaled actors (e.g. when animating scale)

---

plugins/pip/PopupWindow.vala

Don't resize the button returned by create_close_button (). It's
already scaled properly for HiDPI.
Fixes: https://github.com/elementary/gala/issues/280

PiP: Fix wrong size close button on HiDPI

---

data/gala.css
src/ShadowEffect.vala
src/Widgets/WindowClone.vala
src/Widgets/WorkspaceClone.vala

It's not ready to merge until @elementary/ux fixes the CSS ;)

Render shadows using Gtk

---

src/WorkspaceManager.vala

Fixes #274 
Fixes #293 
Something about pulling workspaces out from under mutter while it was trying to assert there wasn't a sticky window left behind on one of them was what was causing the crash.
You can reproduce the gala crash in master with any window if you mark it as always on all workspaces and then close it. It just so happened that the logout dialog and onboard are sticky by default.

Don't remove workspaces for sticky windows

---

src/WindowManager.vala

It's still broken when `workspaces-only-on-primary` is disabled, but at least it seems to fix #326 with the default settings.

Fix #326 by repositioning wallpapers during transition

---

src/DBus.vala
src/SessionManager.vala
src/meson.build

Fixes #324 
Implements `org.gnome.SessionManager.EndSessionDialog` and forwards DBus calls to the session indicator in wingpanel. This is done so that we have consistency when it comes to owning GNOME specific DBus interfaces.
Worth mentioning is also the original reference implementation of the same interface in Budgie Desktop: https://github.com/solus-project/budgie-desktop/blob/master/src/wm/shim.vala

Implement EndSessionManager

---

lib/Utils.vala

In juno, it appears that windows on the non-primary monitors now return `false` on `window.is_always_on_all_workspaces ()`, this made it so gala thought that there was always a window on in this function. I've modified the code to use the property `on_all_workspaces` instead of the function. This works even if making false the property on `gsettings org/gnome/mutter/workspaces-only-on-primary`
fixes #347

Fix multi-monitor windows preventing workspaces from closing automatically 

---

plugins/pip/PopupWindow.vala

Fixes #422.
Fixes a glitch where the `appears_focused` property would change before the window got unmanaged and therefore show the PiP window for a split second before closing it. We now check if the window actor is still shown and if not, we don't do anything.

Fix visibility glitch

---

src/WindowManager.vala

This was accidentally removed in #330 and is the major reason why window menus aren't appearing.

Restore daemon watch

---

src/ScreenshotManager.vala

Implements `flash_area` and adds support for the `flash` DBus parameter.
The area is flashed after reading the pixels into the image surface and before saving the screenshot to a disk so that there is no collision in the process of taking a screenshot.

Implement flash area

---

src/ScreenshotManager.vala

Save screenshots to screenshot folder, fixing: https://github.com/elementary/gala/issues/216
It's an alternative approach to: https://github.com/elementary/default-settings/pull/99 in that it let's Gala create the Pictures folder when it's not available.

Save screenshots to (self created) screenshots folder

---

src/ScreenshotManager.vala

This fixes a large lag when the image is being saved into a file when taking a screenshot. Mostly noticeable on HDD's. This changes all exposed method signatures to async but doesn't affect callers in any way.

Do not block drawing the stage when saving the image

---

src/ScreenshotManager.vala
src/Widgets/SelectionArea.vala

Fixing: #311 
Using 2 signals to differentiate between captured and cancelled just like the [SelectionArea in Screenshot](https://github.com/elementary/screenshot/blob/master/src/Widgets/SelectionArea.vala).

Cancel area screenshot when pressing esc

---

src/ScreenshotManager.vala

Fixed: #474 
When creating screenshots to save on the clipboard `gsd-screenshot-utils` already [created a temporary file](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/master/plugins/media-keys/gsd-screenshot-utils.c#L288). This broke the new async save_image logic.

Fixed saving screenshot to clipboard

---

src/Widgets/WindowSwitcher.vala

Fixes: #447 
The app switcher doesn't properly use the item padding from plank themes:
Example with a increased `ItemPadding`, the normal Plank:
The app switcher plank:
This PR attempts to properly use it, resulting in:

Fix app switcher left and right padding

---

daemon/MenuDaemon.vala

Fixes #520.
Gala was wrongly requested to toggle the state of windows at the user right-clicking the titlebar of a window. This quickly led to window de-sync and weird behaviour.
We now temporarily block the `activate` signal to prevent this from happening when we update the menu.

Fix window menu sync

---

src/WindowManager.vala

Fixes #503.
Fixes a glitch where a window would be "moved" to the same workspace and then switching to the next workspace would have an animation glitch. This was caused by trying to move the window from first workspace to first workspace. It is worth noticing that this change also results in a bell when moving window from first workspace to previous. This is now consistent with the second behaviour when moving to the right.

Do not try to move a window to left if it is on the first workspace

---

src/Widgets/MultitaskingView.vala
src/Widgets/WindowCloneContainer.vala

Fixes #519.
Previous code only made use of Enter when a window was selected in the current workspace preview. The change now checks if that was successful and if not, then just toggle out of the multitasking view.

Make Enter key enter the workspace even without a selected window

---

src/Widgets/WindowClone.vala

Fixes #505.
Hide the active shape when the drag action is starting and hide it when ending.

Fix white box presence when dragging around a window clone

---

plugins/maskcorners/Main.vala
plugins/notify/NormalNotification.vala
plugins/notify/Notification.vala
plugins/notify/NotificationStack.vala
plugins/notify/NotifyServer.vala

In the plugins code we repeat the following code a lot:
```
#if HAS_MUTTER326
return Meta.Backend.get_backend ().get_settings ().get_ui_scaling_factor ();
#else
return 1;
#endif
```
even though we have a `Utils.get_ui_scaling_factor ()` function. When the code is compiled on systems that don't have mutter 326, this will mean an extra function call, but that seems worth it?
The `gala/src` uses `InternalUtils.get_ui_scaling_factor ()`, but I took that "internal" as something that I shouldn't use for plugins? Maybe the `gala/src/` code should also use `Utils.get_ui_scaling_factor ()`?

Use UI scale util in plugins

---

plugins/notify/NotifyServer.vala

Fixes https://github.com/elementary/switchboard-plug-notifications/issues/41.
As seen in https://github.com/elementary/switchboard-plug-notifications/blob/master/src/Backend/App.vala#L32 we need `true` for the recursive parameter, otherwise the schema won't be found and no settings will be applied.

Fix app notification schema not being found

---

lib/Utils.vala

Only use cached buttons when height matches, fixing dpi switch issue

---

src/Background/BackgroundManager.vala
src/WindowManager.vala

Fixes: #561
Fixes: #13
So this feels a bit hacky, but I don't know of a better way to prevent this automatic second destroy call. See #561 for more information.

Prevent double BackgroundManager destroy

---

data/org.pantheon.desktop.gala.gschema.xml.in
lib/Constants.vala
lib/WindowManager.vala
lib/meson.build
src/Settings.vala
src/Widgets/MultitaskingView.vala
src/WindowManager.vala

Fixes #512
Note that the GSettings are kept because Wingpanel is still using it but will be updated to use the values in the Constant.vala file

Remove duration settings

---

daemon/Main.vala
daemon/MenuDaemon.vala

Ran vala-lint on the daemon directory and fixed any errors/warnings that came up. One thing to note, vala-lint doesn't enforce 4 spaces yet, so I haven't updated these files with new spacing rules yet.
Assuming you have [vala-lint](https://github.com/elementary/vala-lint) installed locally:
```sh
io.elementary.vala-lint -d daemon
```
Assuming you have docker installed locally:
```sh
docker run -v "$PWD":/var/opt/vala-lint elementary/docker:vala-lint io.elementary.vala-lint -d daemon
```

Lint the daemon directory via vala-lint

---

src/WindowManager.vala

Fixes: #582
There was no animation when moving a tiled window on top of another tiled window or when maximizing one of two tiled windows ...
**Before** (slowed down animations)
**After** (slowed down animations)

Fix: Animations for two tiled windows

---

src/Widgets/SelectionArea.vala

Cairo by default draws lines like this:
Translate by 0.5, 0.5 to avoid that.

SelectionArea: Align the rectangle to pixel grid

---

src/ScreenshotManager.vala

Throw an error instead of crashing if there's no window to screenshot.
Fixes https://github.com/elementary/gala/issues/626

ScreenshotManager: Null-check the window in screenshot_window()

---

data/20_elementary.pantheon.wm.gschema.override
data/meson.build
src/Background/SystemBackground.vala
src/Widgets/MultitaskingView.vala
src/WindowManager.vala
src/WorkspaceManager.vala

This PR fixes issues against running upstream gala with mutter 3.3x.
This should fix https://github.com/elementary/gala/issues/634
Every single patch is detailed in this post: https://github.com/elementary/gala/issues/634#issuecomment-551851873
I reported every step as a commit comment in order to understand it more easily.

Fix mutter 3.3x crashes

---

plugins/notify/NormalNotification.vala
plugins/pip/Main.vala
plugins/pip/PopupWindow.vala
src/DBusAccelerator.vala
src/InternalUtils.vala
src/Main.vala
src/ScreenshotManager.vala
src/Widgets/MonitorClone.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WindowClone.vala
src/Widgets/WindowSwitcher.vala
src/WindowListener.vala
src/WindowManager.vala
vapi/Meta-2.metadata
vapi/Meta-3.metadata
vapi/Meta-4.metadata
vapi/Meta-5.metadata
vapi/libmutter.vapi

We are now sure that we have the right symbols available with the right version

Regenerate the vapi using the .metadata files

---

data/meson.build

Fixes the "Gala background services" desktop showing up in Plank

Install gala daemon desktop to autostart, not apps

---

meson.build

If I have multiple mutter versions installed on my system, we end up defining the version flags more than once because of the append. Instead we should probably overwrite previous defines as they include all previous versions anyway.

meson: overwrite mutter defines instead of append

---

lib/Utils.vala
lib/WindowIcon.vala
plugins/notify/Notification.vala
plugins/pip/Main.vala
plugins/pip/PopupWindow.vala
plugins/pip/ShadowEffect.vala
plugins/zoom/Main.vala
src/DBus.vala
src/ShadowEffect.vala
src/Widgets/IconGroup.vala
src/Widgets/WorkspaceClone.vala
vapi/Clutter-6.metadata
vapi/Cogl-6-custom.vala
vapi/Cogl-6.metadata
vapi/mutter-clutter.vapi
vapi/mutter-cogl-6.vapi

These changes allow gala to compile and run against mutter 3.36. I haven't merged the `mutter-clutter` vapi changes into the main file as I couldn't figure out a way to do this efficiently.

Mutter 3.36 support

---

src/DBusAccelerator.vala

Fixes #518 
Turns out these changes happened sooner than GSD 3.36, we just didn't notice.

Backport media keys fixes to earlier GSD versions

---

src/DBusAccelerator.vala

This was added in g-s-d 3.33.0 [0].
Without this I was seeing:
```
gsd-media-keys[1927]: Failed to ungrab accelerators: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “UngrabAccelerators”
```
in the journal from g-s-d.
[0]: https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/GNOME_SETTINGS_DAEMON_3_33_0/NEWS#L8

Support g-s-d UngrabAccelerators API

---

src/WindowManager.vala

This may happen when there's an open menu and the user changes
workspace.
Fixes #766

Fix a crash when meta_window is null

---

src/WindowManager.vala

Fixes #764 
`continue` was meant for `null` or destroyed window.
I believe this is handled in lines above.

Fix for #764

---

data/gala.gschema.xml
src/Widgets/ScreenShield.vala

Since these are new keys, it would be nice to have them RDNN'd correctly so we don't have to migrate them later

Gschema: Move screensaver keys to io.elementary.desktop

---

src/Widgets/ScreenShield.vala

This is something I missed from the screensaver branch and is present in the GNOME implementation of their screen locker.
logind has a DBus property on the system bus that indicates whether the session is locked or not. This is queried by other components.
So, let's ensure we keep that property up to date.

ScreenShield: Set locked hint on logind

---

data/gala.gschema.xml
src/Widgets/ScreenShield.vala

It turns out there was a good reason for using the GNOME key here as there are parts of the gsd-power plugin that also use this key, so we'd want to stay in sync with that:
https://github.com/GNOME/gnome-settings-daemon/blob/9c7574080fb463513aa2c9b2302bb3c9daa1bb14/plugins/power/gsd-power-manager.c#L1270

Use GNOME key for enabling screen locker

---

debian/gala.install

It was only used by the Notification plugin

Remove usr/share/gala

---

src/WorkspaceManager.vala

I was able to produce crashes in gala by doing the following:
* Open multitasking view 
* Create an empty workspace by dragging a window into a new one and then out again
* Begin dragging empty workspace container
* Switch workspace in a manner that would cause the empty workspace to be automatically cleaned up with `<Super><Left>` and `<Super><Right>` while still holding the drag
* Let go of the drag
The simplest solution to this seems to be to cancel any ongoing drags when a workspace is about to be removed, since why are you doing this magic multi hand trick anyway.

Cancel multitasking drag and drop when removing workspace

---

data/gala.gschema.xml
plugins/maskcorners/Main.vala
plugins/maskcorners/Settings.vala

And bump to 6px to match Greenfield
There's no real reason this should be configurable

MaskCorners: Remove radius setting

---

plugins/pip/PopupWindow.vala
plugins/zoom/Main.vala
src/Background/BackgroundSource.vala
src/Widgets/WindowSwitcher.vala
src/WindowManager.vala

Fixes some deprecation warnings. (See https://valadoc.org/gdk-3.0/Gdk.Display.get_device_manager.html)
<strike> Also containes #869, which is necessary to compile. Therefore should be merged after #869. </strike>

Use Gdk.Seat instead of Gdk.DeviceManager to get the pointer position

---

src/Widgets/IconGroup.vala
src/Widgets/WorkspaceClone.vala

Since the mutter 3.36 the highlights in the multitasking view had no transparency. To my understanding the issue was, that the RGB values were not pre-multiplied.
**Master using mutter 3.36**
**This branch using mutter 3.36**

(Re-)Make highlights in multitasking view transparent

---

src/Widgets/WindowSwitcher.vala

Fixes #354
Quits the Alt-tab view and switches back to original app when pressing esc

Cancel alt-tab view when pressing esc

---

src/Widgets/PointerLocator.vala
src/WindowManager.vala
src/meson.build

Fixes #715 
Works when `org.gnome.desktop.interface.locate-pointer`  is set. Again, this uses a hardcoded color, but the animation on this one is much more up for discussion I guess.
Maybe we just want an outline shrinking towards the cursor, or something else completely. But this covers the basic implementation so we can discuss potential changes.

Locate pointer

---

src/Widgets/DwellClickTimer.vala

Instead of hardcoding the size of the click time, scale it to the cursor size

Scale hover click timer to cursor size

---

src/Widgets/DwellClickTimer.vala
src/WindowManager.vala
src/meson.build

Fixes #893 
This uses a hardcoded color (blueberry 300) for now. It may be possible to do something clever and get the accent color from the theme if desired, but I was struggling a bit with figuring out how to get the StyleContext, CssProvider and everything set up to do this.
Note: There's been a PR merged into the a11y indicator that adds a switch to set the necessary dconf key to enable this. But for reference it's `org.gnome.desktop.a11y.mouse.dwell-clicks-enabled`

Add visual indicator for dwell click

---

src/DBus.vala
src/ScreenSaverManager.vala

Gala was exporting two DBus interfaces for the screensaver with identical implementations (the GNOME one and freedesktop one). If we use the g-s-d ScreensaverProxy plugin as proposed in https://github.com/elementary/session-settings/pull/36 , then this implements the freedesktop interface for us and makes the inhibitor work properly too.
That way we no longer need this duplicated interface in Gala.

Remove org.freedesktop.ScreenSaver interface

---

src/KeyboardManager.vala

Looks like this was a typo, there isn't a key called `source` and `sources` is referred to throughout the rest of this file.

KeyboardManager: listen to sources gsettings key

---

src/NotificationStack.vala
src/WindowManager.vala

This caused #917 and having them completely non functional when animations were disabled.

Fix notifications being unhandled when animations disabled

---

src/WindowManager.vala

When scrolling past the first/last workspace, Gala nudges the current workspace to indicate that there's no other workspace in the direction that you are scrolling. This nudge sometimes flickers Gala's background on top of the workspace's clone.
This changes fix this by simplifying the animation. I also replace animating `x` with animating `translation-x`, which improves performance by avoiding any relayout calculations made by Clutter.

WindowManager: fixed nudge flicker and improved performance

---

src/InternalUtils.vala

This method causes a segfault when trying to use Gala as a wayland compositor.
I'm reasonably sure it's not needed under Wayland, and in the case that it is needed, it looks like it would just break the hot corners until we write an alternative.

InternalUtils: Prevent X11 specific calls on wayland

---

src/meson.build

Using libmutter_dep allows to have a future-proof checking for this.

meson: Compare libmutter_dep version instead of checking for mutter336_dep

---

daemon/MenuDaemon.vala
lib/Constants.vala
lib/WindowManager.vala
src/WindowManager.vala

Rationale:
* There is no "minimized" version of a window anywhere on the screen, so the name as I understand it doesn't make sense
* The new name also matches the existing meta+H shortcut (and hopefully makes it easier to memorize)
Instead of only changing the localizable string, I've also renamed all occurences of the word "minimized" that weren't inherited from base classes. Are there any third-party projects that might be affected by this? Should I bump an so version number or similar to indicate a breaking change; or should I revert some of the renames?
I've kept the internal name of the "minimize" shortcut to avoid breaking existing setups.

Rename 'Minimize' to 'Hide'

---

plugins/pip/PopupWindow.vala

`Clutter.DragAction` is gone in mutter-7 (the version above what we're using in 6.0). Let's future proof ourselves and stop using it now.
Only affects the resize button/handle of the PiP plugin, so testing will need to focus around that.

pip: Remove deprecated Clutter.DragAction

---

src/Widgets/ScreenShield.vala

This class' constructor is on the critical path of Gala starting up, so we should use the async versions of these methods. There are already checks in place that the interfaces are ready before using them in all the other methods.

ScreenShield: Use async versions of Bus.get_proxy

---

lib/AppCache.vala

This class is initialized in a static constructor so its in the critical path of Gala starting up. There isn't an async version of `GLib.AppInfo.get_all` and it's an I/O heavy operation that enumerates the desktop files on the system, so we should move this out of the main compositor thread.

AppCache: Rebuild in a thread

---

src/WindowManager.vala

When the background actor was reparent from the `background_group` to the switch desktop container and reparent again in the `background_group` in the same X coordinate, for some reason, it became invisible.
It is a weird bug, because moving the background +/- 1 pixel made it visible.
In the old code:
```
background.x = background.steal_data<int> ("prev-x");
background.y = background.steal_data<int> ("prev-y");
background.x += 1; // This makes the background visible (?)
background.x -= 1; // It also works with "y" (??)
continue;
```
Obviously, the is not the fix of this PR :sweat_smile: Instead of reparenting the background actor and using the real wallpaper in the animation, I clone it and make it invisible. This change also simplifies the code a little bit.
Fix …

Fix #1001: Grey backdrop after switching workspace via gestures

---

src/NotificationStack.vala

Fixes #821 
Instead of using a constant value for the notification width, lets calculate it based on the resolution of the monitor and the width of the notification.

Calculate notification width dynamically

---

src/WindowManager.vala

If you are on a multi-monitor setup, maximizing a window on a secondary monitor causes the workspaces on the primary monitor to  move to the next one, even though the maximized window is not moving. I'm just adding a check on `move_window_to_next_ws ()` to ensure that the window is on the primary monitor before doing any other checks

Don't move to next workspace when maximizing a window on secondary monitor

---

src/GestureAnimationDirector.vala
src/WindowManager.vala

Allow to align the switch workspace animation to physical pixels.
With the current master it is not easy to notice the difference, it is easier to test with https://github.com/elementary/gala/pull/1017
With LoDPI displays, the values returned by `GestureAnimationDirector.animation_value` are integers (0, 1, 2, 3...)
With HiDPI displays, let's say that the scale factor is 2, values will be 0, 0.5, 1, 1.5...
If I understood how scaling works in Gala those should be the right values on HiDPI. However, I don't have a HiDPI display to test this, so I'd appreciate your help testing it for me :smile: 
Fix https://github.com/elementary/gala/issues/1018

Fix #1018: Align multi-touch animations to physical pixels

---

src/Widgets/MultitaskingView.vala
src/WindowManager.vala

Restore the default workspace switch animation time.
The animation was incremented to 400 ms and it should be 300 ms if we want to be consistent with stable.

Faster workspace switch animation when using keyboard shortcuts

---

lib/Constants.vala
src/GestureAnimationDirector.vala
src/Gestures/Gesture.vala
src/Gestures/GestureSettings.vala
src/Gestures/GestureTracker.vala
src/Gestures/ScrollBackend.vala
src/Widgets/MultitaskingView.vala
src/WindowManager.vala
src/meson.build

Partially solves  #993
When the multitasking view is opened, the switch workspace animation is not 1:1 at the moment.
As a user, I'd expect this view to respond to scroll events (like in libhandy) and also to my configured multi-touch gesture (3 or 4 fingers swipe).
At the moment we don't have a way to handle scroll events, so my goal here is to unify how scroll events and multi-touch events are handled in a single interface (`GestureTracker`) that will replace the current `GestureAnimationDirector`.
`GestureTracker` allows to configure different backends, at the moment scroll and in a follow up branch, Touchégg. In the future we can add touch and, when Wayland is ready, get rid of Touchégg.
The diff is already quite big, so I'm going to split this in 2 pull request:
1 - This PR. Add …

Multitasking view 1:1 switch desktop animation with scroll events

---

daemon/MenuDaemon.vala
lib/WindowManager.vala
src/WindowManager.vala

Fix https://github.com/elementary/gala/issues/955
There are some design decisions that need to be taken, so invoking @cassidyjames here:
- We need to decide if we want to flash the window when the screenshot is taken or not
- The screenshot sound is not being played, but the screenshot app doesn't play it for window screenshots :thinking: 
- Maybe we should send a notification when the screenshot is taken indicating the path it is saved at. Extra points if there is a way to open Files when clicking on the notification
- Menu order:
And one quick technical question: Is there a way to share the code that sets the file name with the screenshots app? I'd like to move the generation of the string `_("Screenshot from %s").printf (date_time);` to the D-Bus interface and share that code.

Add Take Screenshot to the header context menu

---

daemon/MenuDaemon.vala

Tried to group these a little better. Open to suggestions
Also, thought it might be better to make the move items insensitive instead of visible to tie the relationship closer with that checkbox, but I can revert that change if it's weird

MenuDaemon: re-order window menuitems

---

daemon/MenuDaemon.vala
lib/WindowManager.vala
src/WindowManager.vala

Fix https://github.com/elementary/gala/issues/1074:  Show "Untile" instead of "Unmaximize" in the window menu when a window is tiled.
Also, the current behaviour is to maximize the window when it is tiled. Fix it to restore the window when the "Untile" menu option is selected.

Fix #1074: Window menu says Unmaximize when tiled

---

src/Zoom.vala

Fix https://github.com/elementary/gala/issues/1094
Follow the user animation settings to enable or disable zoom animations.
Split in 2 commits, one for keyboard shortcuts and the other one for gestures.

Fix #1094: Zoom doesn't respect animations key

---

src/Widgets/ScreenShield.vala

`notify` doesn't work on the `DBusProxy` so we weren't updating the sleep inhibitor in all cases. This may have been preventing the screen shield from inhibiting sleep for long enough to lock first, potentially increasing the duration of the flash of the desktop some people see when waking.
In non animated lock cases (suspend due to lid close), we weren't setting the screen shield to be fully opaque, again potentially increasing the duration of the desktop flash.
We were setting `in_greeter` to true regardless of whether the DBus call to the greeter succeeded. If we catch an error, we'll leave this as false, so more attempts can be made.
Personally, I don't see any improvements on my machine, but these changes may improve things for some people. I've always had a flash of the desktop on …

Minor screen shield fixes

---

data/gala.gschema.xml
src/Gestures/GestureSettings.vala
src/Widgets/MultitaskingView.vala
src/WindowManager.vala
src/Zoom.vala

Fixes #1093 
Gsettings schemas now use gestures for the key and actions for the values. This should allow us to add many many more actions without adding many more keys. It also ensures that a given gesture cannot be assigned to more than one action. But an action can be assigned to several gestures.
We'll need to update Switchboard either in parallel or after this branch

Rewrite gesture schemas

---

src/NotificationStack.vala

The actor size was used to calculate the gap between the notificatification
bubbles. The actor was reporting a bigger height because the window
shadow is taken into account to calculate the height.
Use the window frame height instead of the actor height.

Fix #1112: Adjust gap between notification bubbles

---

src/AccentColor/AccentColorManager.vala
src/AccentColor/ColorExtractor.vala
src/AccentColor/NamedColor.vala

Follow-up to https://github.com/elementary/gala/pull/1104
https://user-images.githubusercontent.com/10796736/116773098-ac05c980-aa53-11eb-8c25-93f3f0563b3b.mp4

Set accent color based on primary color

---

src/Widgets/MultitaskingView.vala

On elementary OS 6, the offset used to calculate if a dock/panel is
placed in the top or bottom of the screen was too high to pick the
dock when the small size is selected in system settings.
Adjust the offset used for Odin.
Fix #1134

Multitasking view: Animate the dock when small size is selected

---

src/Widgets/IconGroup.vala
src/Widgets/IconGroupContainer.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WindowIconActor.vala

Easier to review commit by commit.
I'm not specially happy with the last commit (IconGroupContainer: Force re-layout) but I wasn't able to find a way to force the layout to be recalculated. Suggestions to improve it are welcome.
Fix #1158

Workspaces icons/folders make a weird pattern/shape when changing screen resolution

---

src/Widgets/DwellClickTimer.vala

Add a delay to the dwell click timer animation so the circle is not displayed when the user click quickly.
libinput uses a timeout of 180ms when tapping is enabled. Use that value plus a safety margin so the animation is never displayed when tapping.
Fix #1152

a11y: Delay dwell click timer animation

---

daemon/MenuDaemon.vala

Avoid showing scroll when the desktop context menu is displayed close to
the screen bottom edge.
This behavious was caused by the "push_in" param in the popup
GtkMenuPositionFunc callback:
> Note that moving and possibly resizing the menu around will alter the
> scroll position [...]. In practice, this behavior is only useful for
> combobox popups or option menus
https://developer.gnome.org/gtk3/stable/GtkMenu.html#GtkMenuPositionFunc
Fix #1146

Desktop context menu: Do not show scroll

---

src/ScreenshotManager.vala

In previous versions of GNOME Settings daemon (elementary OS <= 5), saving to clipboard was handled by the daemon. The daemon used to request Gala to save the screenshot in a temp path like "/tmp/gnome-settings-daemon-screenshot-XXXX" and copied the image to the  clipboard from there.
More information: #474
Now, Gala is in charge of copying to clipboard when the take screenshot methods receive an empty filename.
Allow to save screenshot to clipboard when the filename received is empty.
Not changing the save_image_to_file to keep backward compatibility.
Fix #1137
Fix #1122 
Note - Please don't squash and merge or this information will be lost from the git log. Or if squashing, keep both commit messages, please.

Screenshot: Fix copy to clipboard using shortcuts

---

meson.build
src/ScreenshotManager.vala

We currently rely on Screenshot to play the shutter sound. This means that it needs pulseaudio permissions in Flatpak and depending on the app taking the screenshot you might not get a sound when a screenshot is taken.
In addition, no sound was played when a screenshot was copied directly to the clipboard.
Play the shutter sound in Gala to avoid this problems.
**This PR:** Play the shutter after taking a screenshot.
Fix https://github.com/elementary/gala/issues/944
Needs https://github.com/elementary/screenshot/pull/215
Needs https://github.com/elementary/screenshot/pull/216

Play the shutter after taking a screenshot

---

plugins/pip/PopupWindow.vala

DragDropAction changes the "reactive" property of the actors it handles.
Add the DragDropAction to the PiP window so it keeps being reactive.
Fix #1035

PiP: Hide close and resize badges after dragging

---

plugins/pip/PopupWindow.vala

I noticed I introduced a bug in https://github.com/elementary/gala/commit/3c47d9dc54cb424ff2aaea0a4f0463963a5f118c: The window click event was triggered on the close/resize button common surface.
Revert that commit and fix the issue in a different way.

[Regression] PiP: Hide close and resize badges after dragging

---

.editorconfig

Avoid linter issues by automatically removing trailing white spaces.

editorconfig: Add trim_trailing_whitespace

---

daemon/Main.vala
daemon/meson.build
meson.build
src/Main.vala
vapi/config.vapi

Provides the directory where the locales are actually installed.
We are [packaging this](https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-895720580) in NixOS, and due to NixOS 's special `localedir`, we cannot apply the translations without this patch.
Thanks in advance for reviewing this :-)

l10n: Correctly setup the locales

---

src/Widgets/IconGroup.vala

Resize is then calling draw which requires icon_container to exist.

IconGroup: Resize the canvas after objects creations

---

lib/gala.deps.in
lib/meson.build

Avoid double inclusion in plugins.

deps: Put the right libmutter name in the .deps file

---

src/Widgets/WindowSwitcher.vala

- Use elementary Palette colors by default
- Remove transparency (at least for now)
- Use the user's selected accent color for the icon highlight
- Simplify creation of variables and only override for dark preference
There may be a better way to get and set the accent color, and if possible, I'd like to get the palette colors from the system stylesheet as well. I'd also still like to get a shadow on this, but I think this is far more legible than the current branch.

WindowSwitcher: Use accent and palette colors

---

src/Widgets/WindowSwitcher.vala

Draw the background of the switcher from a Gtk.StyleContext instead of hardcoding background/foreground/radius information
While here:
* Change the icon size to supported size
* Make sure we're drawing at integer values

WindowSwitcher: draw from Gtk.StyleContext

---

src/Background/Background.vala
src/Widgets/ScreenShield.vala
src/Widgets/Tooltip.vala
src/WindowManager.vala
vapi/Clutter-9-custom.vala
vapi/Clutter-9.metadata
vapi/mutter-clutter.vapi

They are being copied when retrieving as they are simple structs.
Closes #1243

Do not use color properties directly

---

src/Background/BackgroundSource.vala

The lambda function wasn't capturing the value of "i". Instead, "OPTIONS.length" was always used.

Fix crash changing wallpaper

---

src/ScreenshotManager.vala
vapi/mutter-clutter.vapi

This partly reverts mutter 3.38 changes introduced in 87d51c50fbd5a28d2d0d6c3872b4e15e39c9131a.
- https://github.com/NixOS/nixpkgs/issues/139404
- https://github.com/NixOS/nixpkgs/pull/139163
- https://github.com/elementary/gala/pull/980
---
@davidak I think this should work, would you like to test this (by adding [this patch](https://patch-diff.githubusercontent.com/raw/elementary/gala/pull/1259.patch) to gala and rebuild your system) and maybe provide some logs for the upstream?
Update: Downstream PR available at https://github.com/NixOS/nixpkgs/pull/139491.

Fix session crash when taking screenshots with mutter 3.38

---

data/gala-x11.service.in
data/gala-x11.target
data/meson.build
meson.build
meson_options.txt
src/WindowManager.vala
vapi/systemd.vapi

Adds support for launching gala via the new systemd support in `gnome-session`. This has no effect on the current way of doing things as we're still using the `--builtin` flag on our session in session settings, but it prepares us for the future.
I've made this an option in meson so that distributions without systemd can use the old XDG autostarts way of launching gala in the future if they wish.
This can be tested in conjunction with https://github.com/elementary/gala/pull/1255 and https://github.com/elementary/session-settings/pull/55. If you remove the `--builtin` flag from `/usr/share/xsessions/pantheon.desktop`, `gnome-session` will launch Pantheon using the systemd units instead of the XDG autostarts.

Add systemd units

---

data/gala-daemon.desktop
data/gala-wayland.desktop
data/gala.desktop

This is a prerequisite for https://github.com/elementary/session-settings/issues/17 but it has no effect on the current way we're doing session management.
See: https://manpages.debian.org/experimental/gnome-session-bin/gnome-session.1.en.html
This just prevents `gnome-session` from autostarting gala if systemd is launching the session instead, which it isn't, currently.
All of the gsd autostarts already have this property and they still function.

autostarts: set hidden under systemd

---

src/WindowManager.vala

Requires https://github.com/elementary/gala/pull/1270
----------------------
When the multitasking view is opened and a the keyboard shortcuts are used to switch between workspaces, avoid showing the nudge/bump animation on the non-primary display.
Partially address #927

Multitasking View: Show nudge animation only on the primary display

---

src/WindowManager.vala

Don't try to launch non-existent actions if action settings keys are empty. Also DRY
Stops a terminal warning I was seeing

WindowManager: handle empty action keys

---

src/Widgets/MultitaskingView.vala
src/Widgets/WindowClone.vala
src/Widgets/WorkspaceClone.vala

This fixes a terminal error about setting a non-existant custom easing mode. Presumably the original author intended to have "no" easing mode, which should mean `LINEAR`
Also removed the constant `ANIMATION_MODE` while we're here since that just obfuscates what the actual easing we're setting here is

MultitaskingView: don't set custom easing mode

---

src/Widgets/Tooltip.vala

Fixes a crit in Terminal:
```
(gala:297380): Clutter-CRITICAL **: 10:48:57.281: clutter_actor_remove_child: assertion 'CLUTTER_IS_ACTOR (child)' failed
```

Tooltip: null check text_actor before removing

---

src/WindowManager.vala

I've got into a situation a couple times where no dim effect is applied and then when the window is closed the dim is added. Oops

WindowManager: explicitly dim and undim

---

data/gala.appdata.xml.in
src/WindowManager.vala

dialogs fall down on top of windows instead of shooting out of them
https://user-images.githubusercontent.com/7277719/140624875-111a582f-d703-4383-b6cf-1a5a2abe3dc6.mp4

WindowManager: dialogs fall down

---

debian/control

After merging the new alt+tab we don't use this anymore

Control: Remove plank build dep

---

data/meson.build
meson_options.txt

On NixOS, `dep_systemd.get_pkgconfig_variable('systemduserunitdir')` returns a path we cannot write 😭

build: add systemduserunitdir option

---

data/gala.appdata.xml.in
src/Widgets/WindowClone.vala

this seems to solve an issue where the shadows of SSD windows (like Gtk.FileChooser) were being clipped

WindowClone: Include spread in bounding box

---

src/Widgets/WindowSwitcher.vala

Repaint the window switcher indicator when the accent color changes.
Fix #1316
---------------------------------
cc @danrabbit 
Because I think she is working on the GTK 4 style sheet. I'd be nice to know if this approach will work on a GTK 4 world or we'd need to add a new API to Granite similar to `prefers-color-scheme` but for accent colours.

WindowSwitcher: Follow accent color

---

src/Widgets/WindowSwitcher.vala

Since 0c64b60729002131e08bf5ce4e489f7a05a9e135 the window switcher indicator shows artifacts as background.
Clear it before painting to make sure the background is properly displayed.
Here is what I mean with artifacts:
https://user-images.githubusercontent.com/1335948/143718603-48191fd5-34e1-456a-b9c9-64e966bec042.mp4

WindowSwitcher: Clear indicator background

---

data/gala.appdata.xml.in
src/Dialogs.vala
src/WindowManager.vala
src/meson.build

Use our implementation of  `org.freedesktop.impl.Portal.Access` to show the display change dialog. there's a issue when switchboard-plug-display is open that makes all dialogs  spawn at (0,0). i don't know if it is fixable here or in the plug.
we can make this a sort of "frontend" by getting the backend bus name the same way xdg-desktop-portal gets it, if wanted.
fixes #1306

Dialogs: add AccessDialog class

---

src/Widgets/WindowSwitcher.vala

I noticed that I was not able to click some windows underneath the new alt-tab switcher.
Here is my hypothesis why this was only rarely noticed (one other report here: https://github.com/elementary/gala/issues/1322 but seemingly with a different cause?):
The container of the switcher stays reactive, however it is pushed underneath the **active** window, meaning no harm is done. However, **inactive** windows are not raised above the switcher, meaning clicks on inactive windows get absorbed by the invisible switcher.
As part of this PR, I extracted all logic that concerns showing/hiding into a toggle_display method, mostly for my own sanity that all "show things" are also properly undone when hiding. The minimal change to fix this behavior would have been to set `container.reactive = …

switcher: fix container staying reactive in scene

---

src/Widgets/WindowSwitcher.vala

Resolves #1323 . This fixes an off-by-one adjacent error that left the indicator off by an amount based on the scale factor times the children.
The fix can be verified by logging the values for the container.width - (indicator.x + indicator.width) for the final item in the window, and ensuring it is the same as the indicator.x value for the first item in the window.
We will never divide by zero due to the check at the top of the function exiting if the children count is zero.

1323: Always subtract from nat_width the scaled padding over children count

---

src/Background/BackgroundManager.vala
src/Dialogs.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WindowClone.vala
src/Widgets/WorkspaceClone.vala

Workspace clones in the multitasking view haven't been resizing when monitors change (as for example reported in  #484). This should fix it.
Note: the PR contains two unrelated fixes:
* there was a segfault on monitor changes when gala was started from a context where the portal could not be acquired (e.g. when started from a TTY for debugging purposes)
* windows can apparently have NULL titles, e.g. spotify creates a somewhat broken window. Adding the empty string as fallback removes a lot of noise from the output for failed assertions.

fix workspace clone not resizing on monitor change

---

src/Widgets/WindowClone.vala

The API Granite.CloseButtonPosition has been deprecated [1].
Remove it from Gala and always place the close button on the left of
the window in the multitasking view.
[1] https://github.com/elementary/granite/pull/568

WindowClone: Remove Granite.CloseButtonPosition

---

src/InternalUtils.vala

While studying Gala code it was noticed that an if clause contained an `OR` statement where one condition could never be `true` since it already been dealt with earlier in a switch clause.
In order to keep the behaviour the same as at present, the redundant if statement is just removed. Plugin areas are still not added in the case of InputArea.FULLSCREEN.

Remove redundant test

---

src/Widgets/MultitaskingView.vala

This works well in conjunction with https://github.com/elementary/switchboard-plug-keyboard/pull/400 , allowing the multitasking view to be closed again with another Super keypress.
There doesn't seem to be any additional work needed to get it to play nice with the other options for the Super key. Opening either the applications menu or the shortcut overlay with the super key also closes the multitasking view, which I guess is what we would expect.

Allow super key in multitasking view

---

debian/control

Since we're now using the access portal for display settings confirmation and force quit dialogs, we should runtime depend on it

Control: runtime depend on elementary portals

---

src/Widgets/Tooltip.vala

Hi! This is a elementary OS 7 bug. I'm not sure whether we are already focusing on v7 on the `master` branch or if I should add a `#ifdef`. 
---------------------------
Previous to Mutter 10 it was necessary to set the text size to large in order to avoid displaying a tiny text in a Clutter.Text.
With Mutter 10, the default text size matches the system font size and the workaround is no longer necessary.
Before:
After:

[OS 7] Tooltip: Remove text size workaround for Mutter 10

---

data/gala.gschema.xml
src/WindowManager.vala

Fixes #1395 
The GNOME GSettings key we were piggybacking for this was deprecated a long time ago and mutter has finally stopped exposing those events. So, lets set up our own key.
This will require some work in the keyboard plug to change the setting on this key instead.

Move panel-main-menu schema in house

---

daemon/MenuDaemon.vala
data/gala.gschema.xml
src/WindowManager.vala

Fixes #1410 
Since GNOME 42, `gnome-shell` handles the screenshot keybinding and it has been removed from GSD, so we have to re-implement it here.

Move screenshot shortcuts in-house

---

src/Widgets/WindowSwitcher.vala

Fixes #1412 
The `get_origin ()` method of the `ActorBox` from the `allocation` property appears to be returning `inf` (infinity?) when I printed the X and Y float values, so making this change seems to resolve the issue.

Fix initial alt-tab switcher indicator visibility.

---

src/Widgets/MultitaskingView.vala

Removing this fixes a bug where scrolling in multitasking view closes it in OS 7.
I'm not really sure what the original intention here was. I tried to get back through get history to get a clearer picture:
* https://github.com/elementary/gala/commit/5adb6566f6f42bb6affa548ba66b0c996e6bc79c
* https://github.com/elementary/gala/commit/4ec9f2e6b6b5c7bd7f59e22affdb289299ab3756
* https://github.com/elementary/gala/commit/96748eededb0fa82456396aad79409d67578aceb
Afaict all keyboard interaction still works as expected without this

MultitaskingView: Remove key_focus_out override

---

src/WindowManager.vala

Instead of checking this condition twice, we can just set the value directly when we check it the first time

WindowManager: set workspace switch duration directly

---

src/Widgets/WindowClone.vala

Review with "hide whitespace changes". No logical changes, only namespacing and indentation.
* Put `Gala` namespace inline
* Make classes used in WindowClone private to this class so we have one class per file
* Explicitly namespace Clutter and Meta
* Update copyright header while we're here

WindowClone: explicit namespace, make internal classes private

---

src/Dialogs.vala

Depends on a release of icons with https://github.com/elementary/icons/pull/1107

Dialogs: use computer-fail for force quit dialog

---

src/Widgets/MultitaskingView.vala

Fixes the spam of the following assertion that we get when opening and closing the multitasking view:
```
clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
```
This is because `dock_clones` is just an empty actor used to contain the clones of the dock and wingpanel. It initially doesn't have an allocation, and we never change its position, so we don't need to offset by it.
This code is responsible for animating wingpanel and plank in and out during the toggling of multitasking view. It appears to still work manually opening the view, but I haven't tested gestures.

Fix multitasking view allocation assertions

---

src/Widgets/WindowClone.vala

We always want to listen to the click signal.
Fixes #1442

WindowClone: Always add the click action

---

src/WindowManager.vala

Fixes #1354
The multitasking view has its own cloned view of the workspaces and windows that it animates, so we don't need to be animating the actual workspaces and windows behind it, which messes up our window clones.

Don't animate workspaces behind multitasking view

---

lib/gala.deps.in

We are now exposing Posix.pid_t in the public API for the Application management.
Closes #1471

Add posix to the list of Vala dependencies

---

lib/AppSystem.vala

`get_wm_class` and `get_wm_class_instance` in Mutter can return `null` which we were passing to our non-nullable methods. So I was getting a bunch of criticals in my logs.

AppSystem: make wmclass nullable

---

src/Widgets/MultitaskingView.vala

Easing wasn't being correctly used when scrolling between workspaces with the touchpad in the multitasking view. There were two problems with this: scrolling seemed to lag behind the user's fingers sometimes, and letting go of the touchpad would almost always cause a jarring jump.
This little patch fixes both of these issues, making everything silky smooth.
If someone's not clear on what specifically we're solving here, I could record my screen and my hand on my touchpad before & after this patch. It really is night and day.

Fix awkward two-finger scroll in multitasking view

---

src/Widgets/WindowClone.vala
src/Widgets/WorkspaceClone.vala

This animation is currently super stuttery, especially on high-resolution devices. It was getting on my nerves. The reason it's slow is because we constantly reallocate resources instead of just scaling the actors we already have. On top of that, we also allocate a new texture every single time a `FramedBackground` was painted. Allocating stuff in the render loop is generally a bad idea.
So I removed a bunch of seemingly useless code and started caching resources in `FramedBackground` - and now it runs at 240fps on my laptop even with power savings enabled!
This is marked "draft" because I have no idea what I'm doing, and I assume there was a good reason for all the complexity inside `WindowClone.allocate`. That being said, after mercilessly ripping out all that code, everything seems to …

Improve multitasking view animation performance

---

data/gala.css
src/ShadowEffect.vala
src/Widgets/WindowClone.vala
src/Widgets/WindowSwitcher.vala
src/Widgets/WorkspaceClone.vala

Fixes #1203
Before:
After:
Remove unused `window_spread` property.
Introduce a new `window-clone` css class with `border-radius: 0;` corners for WindowClone
Reuse values from `get_bounding_box` in `modify_paint_volume`

WindowClone: Fix shadows

---

src/Dialogs.vala

we don't want to calls to the portal to be timedout before the user sent a response, so disable the timeout.
while here, fix a issue with the show() call in the CloseDialog class creating new dialogs even when a dialog is already open, also handle the portal response only in the AccessDialog base class now and use a class callback to convert betwwen portal and close dialog responses.
fixes https://github.com/elementary/gala/issues/1505

Dialogs: Remove DBus Timeout From AccessDialog Call

---

src/Dialogs.vala
src/WindowManager.vala

the value of 30 seconds here is wrong, and the dialog was outliving the timeout used by mutter internally. instead of hardcoding the right values here too, use the mutter provided function to query the real timeout.
also, make `AccessDialog.show()` base handler run first than signal callbacks, and that we only call `AccesDialog.close()` when we don't receive a response.

WindowManager: `confirm_display_change()` Fixes

---

data/gala.appdata.xml.in
src/ScreenshotManager.vala
src/Widgets/MultitaskingView.vala

Resolves #24
- Allow switching workspaces using Super+1-9, Super+Tab, Super+Shift+Tab, Super+Home, Super+End

Extend list of allowed keybindings in multitasking view

---

src/Widgets/WorkspaceInsertThumb.vala

Review with "Hide whitespace"
* Inline namespace
* Explicit Clutter and Meta namespaces
* Explicit `private` keyword
* Update copyright

WorkspaceInsertThumb: Code style fixes

---

src/Widgets/WindowClone.vala

This was added in #1464 to _fix_ #1442 while (I think) the actual solution was in #1468.
Fixes the issue where clicking windows on other workspaces in multitasking view triggers them instead of changing workspace.

WindowClone: Add click action only in overview mode

---

plugins/pip/Main.vala

Fixes #849 
When choosing a PiP region for certain windows with server-side decorations (such as shadows), the clipped window we displayed in the PiP overlay would be ultimately offset by (what I believe is) the Gala-side decorated area of the window - that is, the window shadow.
What this means is that for most apps, users would see a slightly different region of the window than they chose. This didn't happen for all applications, but it did happen for some very common ones (Firefox, Chrome, Terminal...)
This patch makes it so that we now take this into account before setting the clip rect for the PiP view.

Fix PiP positioning offset

---

lib/DragDropAction.vala

Dragging PiP views was practically impossible on my end; once I started dragging a PiP window, it would stop listening for any further drag events and I'd need to let go and start dragging again if I wanted to move it more than ~30px.
I assume there was a good reason reactivity was being disabled here, so that's why I'm marking this as a draft. I haven't noticed any adverse effects from removing this line, and PiP is now usable on my end.
Before:
https://user-images.githubusercontent.com/1385480/209759009-eacb95ed-a828-465b-a185-a62d448a523b.mp4
After:
https://user-images.githubusercontent.com/1385480/209759019-743772ff-051c-491f-868b-08122f841953.mp4

Draft: Fix PiP window being undraggable

---

src/Widgets/WindowClone.vala

Fixes this warning:
```
** (gala:15925): CRITICAL **: 15:41:55.603: gala_drag_drop_action_get_dragging: assertion 'self != NULL' failed
```

 WindowClone: Fix warnings in window overview

---

lib/Utils.vala
src/WindowManager.vala

Fix compile warning and reuse window snapshot in maximize animation

Cleanup after #1557

---

data/gala.appdata.xml.in
src/WindowManager.vala

Resolves #1081
Also fixes a bug where trying to move window to non-existing workspaces resulted it stuck to top when switching workspace afterwards.

Unify move to workspace behaviour

---

src/Widgets/IconGroup.vala
src/Widgets/WindowClone.vala
src/Widgets/WorkspaceClone.vala

Fixes #1578 
Also now close buttons in multitasking view trigger when released instead of when pressed.

Use ClickAction for FramedBackground and close buttons

---

src/Widgets/MonitorClone.vala
src/Widgets/WorkspaceClone.vala

We need to restack clones only for correct animation, so instead of restacking our clones every single time windows are restacked, restack them before animating.

Don't connect to Meta.Display.restacked

---

data/gala.gschema.xml
src/KeyboardManager.vala
src/WindowManager.vala

These keybinding were removed in https://code.launchpad.net/~ntnk/gala/modifiers-only-input-source-switch because Gnome Shell didn't have them at the time. But currently Gnome Shell supports both ways of switching keyboard layouts, so makes sense add it back.
This allows us to set shortcuts such as Super+Space to switch keyboard layouts.

Add keybindings for switching input source

---

plugins/maskcorners/Main.vala
src/Background/BackgroundContainer.vala
src/Background/BackgroundSource.vala
src/HotCorners/HotCornerManager.vala
src/NotificationStack.vala
src/Widgets/MultitaskingView.vala
src/Widgets/PointerLocator.vala
src/Widgets/WindowSwitcher.vala
src/WindowManager.vala

Shrinks the diff of #1570 by getting the `MonitorManager` in a way that is also compatible with Mutter 44

Get MonitorManager from context

---

src/KeyboardManager.vala

`Meta.Backend.get_backend ()` doesn't exist anymore in Mutter 44, so we can shrink the diff of #1570 here by getting it from the display context instead.

KeyboardManager: get backend from context

---

src/InternalUtils.vala
src/Widgets/PointerLocator.vala

This in theory allows the `PointerLocator` widget to support non-integer scaling factors, and per-monitor scaling factors. Haven't tested either of these things, but the normal LoDPI/HiDPI support seems to still work.
This will reduce the diff of #1570 , as we can't assume a single global integer scaling factor anymore with newer versions of mutter.

PointerLocator: Support floating, monitor specific scale

---

lib/DragDropAction.vala

In master `actor_clicked` is triggered even if you only release mouse button on actor without actually clicking it.

DragDropAction: Check that actor was actually clicked

---

src/WindowManager.vala

`Meta.Util.later_add` is removed in newer versions of Mutter. We can do this to prepare for Mutter 44 and reduce the diff of #1570

WM: Add laters via compositor

---

lib/Utils.vala
plugins/maskcorners/Main.vala

Reduces the diff of #1570 by allowing a per-monitor, non-integer scale factor for the corner masks.

maskcorners: Scale corner masks per-monitor

---

src/ScreenshotManager.vala

Only affects the naming of saved screenshot files, but in theory allows this to support non-integer and per monitor scaling factors.

ScreenshotManager: Support non-integer scaling factors

---

src/WindowManager.vala

Review with whitespace changes hidden.
In Mutter 44, Gala crashes on startup due to trying to initialize GTK before Gala is fully initialized. This is the same issue we have trying to start Gala in Wayland mode, but we will have it in Mutter 44 in X11 mode too.
If we manually initialize GTK and all of our GTK dependant things in a "later", we can delay the initialization of GTK until a point where the compositor is ready to accept connections from GTK.
This fixes the crashing issue with Mutter 44 in X11 mode. It may unblock Wayland too, but I haven't tested yet.
I've been testing this for a bit and haven't noticed any regressions yet, but it'll need some testing, especially around the functionality that has been moved into this block.

WM: Init things that depend on GTK later

---

src/KeyboardManager.vala

In `master` on startup keyboard indicator may show current keyboard layout as Russian but the real selected layout is English. This PR sets current a keyboard layout on startup preventing the bug.

KeyboardManager: Set keyboard layout on startup

---

lib/Utils.vala
plugins/pip/PopupWindow.vala
src/Widgets/IconGroup.vala
src/Widgets/WindowClone.vala
src/Widgets/WorkspaceClone.vala

Needed to reduce the diff of #1570 
The also adds the ability to cache close button pixbufs at multiple sizes, ready for a world where we potentially have multiple scaling factors in use at once.
Testing should involve anything with a close button (windows in Multitasking View, PiP windows, and the Icon Group containers at the bottom of the Multitasking view)

IconGroup: Support floating scale factors

---

src/Widgets/IconGroupContainer.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WorkspaceInsertThumb.vala

Updates `IconGroupContainer` and `WorkspaceInsertThumb` to have a settable scale factor, meaning that the parent widget that manages these can set the scale factor on the instances of these widgets. This means they can in theory be used on multiple monitors with differing scale factors in future.
But for now, the LoDPI/HiDPI support still works, and this reduces the diff of #1570

WorkspaceInsertThumb: Support floating point scale factors

---

src/Gestures/GestureTracker.vala
src/InternalUtils.vala
src/Widgets/WindowClone.vala

To get to the nearest physical pixel and fit on the grid, we just need to round to the nearest integer, we don't need to know the scale factor.

InternalUtils: Remove pixel_align method, and just round

---

src/Widgets/MultitaskingView.vala

Fixes #1519 
This resolves a bunch of issues with MultitaskingView and multiple monitors.
We were forcing the size of the `MultitaskingView` Actor to be the size of the primary monitor, when in reality, it also contained Widgets destined for other physical monitors. If we move the stuff we want to be on the primary monitor into a separate child Actor, and size _that_ to the size of the primary monitor, then stuff is less broken.

MultitaskingView: Ensure MonitorClones are visible on other monitors

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala
src/Widgets/WindowSwitcher/WindowSwitcherIcon.vala
src/meson.build

Preparation for https://github.com/elementary/gala/issues/1547
Fixes FIXME in the code:
```
// For some reason, on Odin, the height of the caption loses
// its padding after the first time the switcher displays. As a
// workaround, I store the initial value here once we have it
// and use that correct value on subsequent attempts.
```
and
```
// FIXME there are some troubles with layouting, in some cases we
//       are here too early, in which case all the children are at
//       (0|0), so we can easily check for that and come back later
```

WindowSwitcher: Merge icon and indicator

---

src/Widgets/IconGroup.vala

IconGroup: Correctly set highlight opacity on start

---

lib/DragDropAction.vala
plugins/pip/PopupWindow.vala
src/Background/BackgroundContainer.vala
src/Gestures/Gesture.vala
src/Gestures/GestureSettings.vala
src/Gestures/ScrollBackend.vala
src/Gestures/ToucheggBackend.vala
src/InternalUtils.vala
src/ScreenshotManager.vala
src/Widgets/IconGroup.vala
src/Widgets/MultitaskingView.vala
src/Widgets/PixelPicker.vala
src/Widgets/SelectionArea.vala
src/Widgets/WindowClone.vala
src/Widgets/WindowOverview.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala
src/WindowManager.vala
src/Zoom.vala
vapi/Clutter-10.metadata
vapi/Clutter-11.metadata
vapi/mutter-clutter.vapi

Also avoid to use Gdk.Display when we have already everything from Mutter.

Avoid to use Gdk constants when Clutter should be used

---

lib/Utils.vala
meson.build
src/Gestures/GestureTracker.vala
src/InternalUtils.vala
src/Widgets/MonitorClone.vala
src/Widgets/WindowClone.vala
src/Widgets/WindowCloneContainer.vala
src/Widgets/WindowOverview.vala
src/Widgets/WorkspaceClone.vala
src/WindowManager.vala
vapi/Clutter-12-custom.vala
vapi/Clutter-12.metadata
vapi/Cogl-12-custom.vala
vapi/Cogl-12.metadata
vapi/Meta-12.metadata
vapi/libmutter-12.deps
vapi/libmutter-12.vapi
vapi/libmutter.vapi
vapi/meson.build
vapi/mutter-clutter-12.deps
vapi/mutter-clutter-12.vapi
vapi/mutter-clutter.vapi
vapi/mutter-cogl-12.deps
vapi/mutter-cogl-12.vapi
vapi/mutter-cogl-pango-12.vapi
vapi/mutter-cogl.vapi

Add support for Mutter 44

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala

Closes #1343
Fixes some issue when using window switcher for the first time in the session caused by `current_icon` being `null` and also issue caused when minimizing the active window and immediately using Alt+Tab.

WindowSwitcher: Fix issues on first use and after minimize

---

src/Widgets/WindowClone.vala

Fix double icon when crossing icon group

---

.github/workflows/main.yml

Avoid specifying the mutter version per container.

ci: Use any available mutter version

---

data/gala.metainfo.xml.in
plugins/pip/PopupWindow.vala

PiP: Check workspace before hiding the window

---

src/WindowManager.vala

Fixes #1331
That's an ugly solution but I guess it's the only working one. For some reason when double commander destroys its dialogs they no longer have transient window, because of that the undim failed.

Keep track of dimmed windows

---

data/gala.metainfo.xml.in
src/WindowManager.vala

Reverts elementary/gala#1688
Update metainfo
Fixes https://github.com/elementary/gala/issues/1712

Revert "WindowManager: Remove Meta.Later"

---

lib/WindowManager.vala
src/WindowManager.vala

Fixes an issue described [here](https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/216#issuecomment-1627708086).

Improve handling of move-to-workspace shortcut

---

src/Widgets/MultitaskingView.vala
src/WindowManager.vala

1. Remove unused constant in MultitaskingView
2. Make WindowManagerGala.NUDGE_GAP integer
3. Add missing `unowned`
4. Move `switch_workspace`'s `window_created` listener to the method itself.

WindowManager: A small cleanup

---

.github/workflows/main.yml

This allows us to specify the mutter version instead of using globs (useful as some Ubuntu version have two mutter version in the repository while transitioning to the next version)

ci: Specify the mutter package to use

---

src/WindowManager.vala

For some reason it breaks Wayland session. Needs to be tested on other distros.

Don't use Gtk.init

---

src/Background/BackgroundSource.vala

Also use a GLib.HashTable instead of Gee.HashMap as it is enough for here.

BackgroundSource: Keep a reference to the monitor manager

---

plugins/pip/PopupWindow.vala
src/Widgets/WindowClone.vala

Fixes clipped shadows in multitasking view:

Increase `window-clone` shadow size

---

src/Widgets/WindowClone.vala

In `master` cursor sometimes didn't reset because `WindowClone.drag_end` has a bunch of returns.

WindowClone: reset cursor early

---

data/gala.metainfo.xml.in
lib/Utils.vala
src/WorkspaceManager.vala

In `master` `WorkspaceManager` doesn't delete empty workspaces despite window located on second monitor.

WorkspaceManager: count windows on primary monitor only

---

lib/DragDropAction.vala
src/Widgets/WindowClone.vala

Fixes an issue where window icon can get detached from cursor if one is moving it too fast

DragDropAction: pass correct coordinates to `drag_begin`

---

src/WindowManager.vala

The change introduced in #1762 causes a X11 session to crash on Fedora 38. After reverting the change, the session doesn't crash.
On Fedora 38 a Wayland session crashes both with and without the change introduced in #1762.
To fix the issue, GTK should be initialized only in a X11 session.

Gtk.init only in X11 session

---

data/gala.gschema.xml
lib/ActivatableComponent.vala
src/Widgets/WindowOverview.vala
src/WindowManager.vala

The first step towards https://github.com/elementary/gala/issues/485
Removes window spread for one workspace. AFAIK it does the exact same thing as the multitasking view, so it can be removed.
Do not merge until #1777

Remove `expose-windows` shortcut

---

src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/1799
Fixes https://github.com/elementary/gala/issues/1287
Fixes https://github.com/elementary/gala/issues/927
Reuses clones used for workspace switch animation.

Animate nudge with clones

---

src/NotificationStack.vala

Should fix the crash described in https://github.com/elementary/gala/issues/1727#issuecomment-1836488852 and adds more debug messages.

Improve debug messages in notifications stack and add more checks

---

src/DBus.vala
src/DesktopIntegration.vala
src/Widgets/WindowOverview.vala
src/WindowManager.vala

This is going to be used by dock when more than one window is open for an app and the app icon is clicked on.
Uses the WindowOverview but with only the windows that belong to the specific app. Once the dock is properly integrated it will stay as well and don't go away.
Also opinions in general on this? An alternative would be something more classical like the alt tab switcher but with window previews over the dock icon but I like this a bit more and it is as far as I understood it what's meant in #1377.
Mostly fixes #1377 (probably together with #1817, alternatively that can be absorbed here with this handling deciding between focus for one or spread for two or more but I think a window list in the context menu would still be useful in the dock)

Add window spread for an app

---

src/Widgets/WindowSwitcher/WindowSwitcherIcon.vala

Fixes #1834 
`Clutter.Color` uses `uint` whereas `ctx.set_source_rgba` uses `double`
This is a remnant from #1825

WindowSwitcher: Fix accent color

---

src/Background/BackgroundManager.vala

Fixes #1841
Closes #1843 
Ok I did some digging so here is what I found and what I think is happening:
When clip bounds aren't set the full texture size is used as clip bounds. But when the texture isn't loaded yet the size is seen as 0 so clip bounds are set to 0 and the whole texture is clipped away because clip bounds aren't updated when the texture is loaded.
Anyways regardless of whether that's actually what's happening this PR fixes the issue for me without reintroducing #1815 :)

Fix rounded background

---

src/Background/BackgroundManager.vala

When starting gala without changing wallpaper, monitors being updated, etc. rounded corners weren't applied since #1845. This PR should fix that.

Fix no rounded corners on first start

---

src/Widgets/PixelPicker.vala

This seems not to be used? But I'd like @davidmhewitt to confirm :)

PixelPicker: Remove unused canvas

---

daemon/MonitorLabel.vala
data/gala-daemon.css

* In latest Gtk4 the only non-deprecated way to add styles from a string is to the whole display, so prepare for that
* Set label margin in CSS
* Remove some unused styles that were for the display plug

MonitorLabel: clean up styles, gtk4 prep

---

lib/Drawing/Color.vala
src/Widgets/Tooltip.vala
src/Widgets/WindowClone.vala

Slowly going towards #1839 
I've started with harcoding colors from our Gtk theme. In the future it might be better to get them directly from the file but for now I think it's enough to hardcode

Tooltip: Dont use Gtk StyleContext

---

src/Widgets/WindowClone.vala

WindowClone/ActiveShape: Don't use Gtk.StyleContext

---

lib/Drawing/Color.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala

Slowly going towards #1839
While we're here let clutter handle layouting and don't do it ourselves.
I'm not sure whether we need a border or something here. StyleContext.render_frame was called but in the CSS I didn't find any hints to a border or something similar? Also visually it seems to be the same? Although I'm not sure my eyes are good enough to make out a difference :)

WindowSwitcher: Don't use Gtk

---

src/WindowManager.vala

It seems that currently on wayland the window type changes to normal on dialog windows when they are being destroyed so that we don't know they were modal. Therefore instead of checking window type and undimming then we connect to the unmanaged signal and remove the effect when it is emitted. This also cleans up the workarounds we did regarding knowing the transient parent.
Fixes #1800

Fix dim effect removal on wayland

---

src/WindowGrabTracker.vala
src/WindowManager.vala
src/meson.build

https://github.com/elementary/gala/assets/80143868/ea251780-4e67-44f9-98e9-539d052ba345
https://github.com/elementary/gala/assets/80143868/c9905ca0-8b6f-4bc4-b0f2-d0d5e8f7299c

Improve window dragging between workspaces

---

data/gala.gschema.xml

Super + Space is a default shortcut to switch keyboard layouts in almost every other OS. It would be nice if users could use it right away
@danirabbit do we want to do this or leave the manual configuration up to the user?

Set `Super + Space` to switch keyboard layout by default

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala

We don't need gtk settings here since we don't use the gtk theme directly anymore.

WindowSwitcher: Remove Gtk.Settings

---

.github/workflows/main.yml
docs/meson.build

CI currently fails for development target because of some libplank dependency mismatch. But since we don't depend on plank anymore anyways remove it from CI and while we're here documentation.

CI: Remove plank dep

---

.github/workflows/main.yml
src/HotCorners/Barrier.vala
src/HotCorners/HotCorner.vala

Meta.Display is removed from barrier in 46 (and it was deprecated before), so remove it here

Barrier: fix build with mutter 46

---

src/WindowManager.vala

Works both on X (also with plank) and on wayland with #1887.
Fixes #275

WindowManager: Keep docks static during workspace switch

---

src/Background/BackgroundManager.vala

Fixes #1903 
On first creation `background_actor` is still null.
Tbh I'm not quite sure why it worked before or why visible was even being set :)

BackgroundManager: Don't set visible

---

src/ShellClients/PanelWindow.vala

We don't need clone and hide tracker (which does quite a bunch of tracking) stuff if hide mode is set to never so don't create it in that case. Theoretically improves performance :)

ShellClients: Don't keep a clone if we never hide

---

src/HotCorners/Barrier.vala
src/HotCorners/HotCorner.vala
src/HotCorners/HotCornerManager.vala
src/ShellClients/HideTracker.vala
src/ShellClients/PanelWindow.vala

Barriers require the backend since a newer mutter version. Also switch to composition instead of inheritance to prevent this from happening again as well as catching errors if barriers aren't supported.

Fix barriers

---

src/InternalUtils.vala

Copying the list would sometimes lead to absolutly crazy numbers for width and height of some TilableWindow rects. I'm lacking the background knowledge as to why this just started happening now or what was actually going on but in my  testing this seems to fix it. Also it seems as if the algorithm is more stable now and windows don't just randomly change place but maybe I'm just imagining things at this point lol :)
Thanks @bobby285271 for your investigations otherwise I would've been looking into wayland stuff for far too long :)
Fixes #1911

InternalUtils: Fix window placement

---

data/gala.css
lib/Drawing/Color.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala

We need to remove GTK style context for Wayland, but it's being used for both shadows and borders here. Draw our own border here so we can handle drawing our own shadow in a future branch without worrying about the border too
Remove some dead css while we're here

WindowSwitcher: draw our own borders

---

src/ShellClients/NotificationsClient.vala

It's `HAS_MUTTER46` not `HAS_MUTTER_46` :facepalm:

Fix notification focus

---

src/PantheonShell.vala

Had these lying around for some debugging I did so might as well propose them here. They shouldn't appear so won't cause log spam but if they do in the future (maybe because of a mutter change or something) I'd like to know why some panel stuff isn't working :)

PantheonShell: Add more warnings

---

src/ShellClients/PanelClone.vala

While in fullscreen docks are hidden so if we animate we just get the clone flying in and immediately disappearing

PanelClone: Don't animate while in fullscreen

---

src/DesktopIntegration.vala

DesktopIntegration: Switch to correct workspace when focusing window

---

src/ShellClients/PanelWindow.vala

- Update struts on workspace change
- Update struts also on position change not only size
Fixes an issue that would cause the strut to be on the wrong display in some multi monitor setups on first start

PanelWindow: Make struts more reliable

---

src/Dialogs.vala
src/WindowManager.vala
vapi/Meta-14.metadata
vapi/libmutter.vapi
vapi/meson.build
vapi/mutter-cogl-14.deps

The dialog creation methods have to return a full reference.
Also we can assume that the dialog de-duplication work will already be done.

Dialogs: Fix Mutter bindings around dialog creation

---

src/Dialogs.vala
src/WindowManager.vala

Avoids to use hand-made bindings and reuse consistent app name.

CloseDialog: Reuse the Gala.App object to get the user-visible title

---

lib/DragDropAction.vala

We've had a ref cycle here leading to pretty big memory consumption if many workspaces were opened and closed again, since all the backgrounds were kept around.

DragDropAction: Fix memory leak

---

lib/Drawing/Canvas.vala

Currently the bitmap isn't being cleared and the old content is showing even after invalidate is called.
Fixes https://github.com/elementary/gala/issues/1934

Canvas: discard bitmap on invalidate

---

src/Dialogs.vala

Allows to make sure that the object will be the same as the one the function started and will actually not be null.

Dialogs: Use the provided object in finish

---

src/NotificationStack.vala

On wayland the notification shows completely for a frame before the animation starts. Prevent this by explicitly setting opacity and rotation to their initial values.

wayland/NotificationStack: Don't flicker at the beginning of the animation

---

src/DesktopIntegration.vala

Allows to differentiate between them on the dock.

DesktopIntegration: Report wether the window is in the current active workspace

---

lib/DragDropAction.vala

Make sure that we are not holding a reference to the object after handling the dnd action.

DragDropAction: Release hovered reference when finishing the action

---

plugins/pip/PopupWindow.vala

Fixes missing shadow from https://github.com/elementary/gala/issues/1617

PiP: Fix shadow

---

src/WindowManager.vala

Fixes an issue when maximized windows could've had an incorrect stacking order on workspace switch

Sort windows by stacking order before workspace switch

---

po/ru.po
src/ScreenshotManager.vala
vapi/libmutter.vapi

Addresses https://github.com/elementary/gala/issues/2014

ScreenshotManager: Fix saving to clipboard

---

src/ShellClients/CenteredWindow.vala
src/ShellClients/PanelWindow.vala
src/ShellClients/ShellClientsManager.vala

Should hopefully fix #1961 for real this time
Also fixes a memory leak where we were keeping centeredwindows around even after they were unmanaged

ShellClients: Fix crash when positioning window while unmanaging

---

src/ShellClients/CenteredWindow.vala
src/ShellClients/HideTracker.vala
src/ShellClients/PanelClone.vala
src/ShellClients/PanelWindow.vala

If a shellclient window became unmanaged the corresponding panelwindow wasn't actually destroyed due to a ref cycle. This could cause a crash when a client was killed and then launched again and then something about the monitors (e.g. scale) changed. Also it was a memory leak.

ShellClients: Fix memory leak and crash

---

daemon-gtk3/WindowMenu.vala
daemon/WindowMenu.vala
data/gala.gschema.xml
plugins/pip/Main.vala
src/WindowManager.vala
src/Zoom.vala

I think we should RDNN gsettings before OS 8 release because the next opportunity will be OS 9, and it's like a long time from now.
Addresses https://github.com/elementary/gala/issues/271

RDNN keybindings gsettings schema

---

data/gala.gschema.xml
meson.build
src/InternalUtils.vala
src/Widgets/MultitaskingView.vala
src/WindowManager.vala
vapi/config.vapi

Addresses https://github.com/elementary/gala/issues/271

RDNN behavior schema

---

src/Widgets/WindowCloneContainer.vala

Fixes two crashes that regularly appeared when opening multitasking view.
1. the slot of a windowclone can be null as noted in documentation. Without checking it we could crash when opening two windows on the same workspace, move one to another workspace without ever opening multitaskingview. If you then open multitasking view it would crash since it runs a few handlers trying to select another window since in the view of the multitasking view one was "removed" and in the process it will try to access fields on the slot that is null because it's the first time we open so they haven't taken a slot yet. 
2. current_window could be unrefed twice if it was set to null in open which could cause the actor to be destroyed since current_window held the only ref on it. This in turn would cause the …

Fix multiple crashes

---

src/WindowManager.vala
vapi/atk-bridge-2.0.vapi

Fixes #2042
Confirmed build success on:
- elementary OS 8 Early Access (gcc 13.2.0)
- Fedora 40 Workstation (gcc 14.2.1)
Confirmed Gala runs as expected on:
- elementary OS 8 Early Access

Fix building with gcc 14

---

src/Widgets/MultitaskingView.vala

Currently if you open the multitaskingview while a notification is open they are being animated in and out like a normal dock although they should just stay where they normally are.

MultiTaskingView: Fix notifications sliding in and out

---

src/DesktopIntegration.vala

The indicators of the dock change appearance (currently they show/hide or with elementary/dock#270 they change appearance) depending on whether windows are on the current workspace or another so we have to update it when the workspace changes.

DesktopIntegration: Emit windows changed on workspace changed

---

lib/WindowIcon.vala

WindowIcon: reload icon if more info about the window becomes available

---

.github/workflows/main.yml

The stable and unstable images are no longer jammy but noble

ci: Update mutter version for noble

---

src/ShellClients/HideTracker.vala

Fixes #1959 
Fixes elementary/dock#78
The dock gains focus and will stay until it is unfocused, e.g. by tapping another window.

HideTracker: Reveal panel on swipe

---

data/gala.metainfo.xml.in
src/ShellClients/HideTracker.vala

Fixes https://github.com/elementary/gala/issues/2083
HideTracker doesn't take into account that the dock window can be hidden and therefore cannot be hovered. This PR fixes it.

Fix autohide

---

src/WindowManager.vala

Starts addressing #2080 
On main a 100% way to reproduce #2080 is having a maximized window so that the dock is hidden then trying to switch workspace so that a nudge plays and then trying to show the dock again. That is fixed by this PR. However there are more ways to reproduce #2080 so it's not entirely fixed.
#2080 will be fixed by #2094 however this can/should still be merged because the current behavior is just wrong

Fix stacking order after workspace switch

---

src/ShellClients/PanelClone.vala

Fix panel sometimes being behind windows

---

lib/DragDropAction.vala

Fixes #1960
This fixes tapping a window in the multitasking view to select it.
A warning was generated along the lines of assertion event type == BUTTON_PRESS/RELEASE/etc. failed.

DragDropAction: Fix actor_clicked emission on touch event

---

lib/AnimationsSettings.vala
lib/WindowManager.vala
lib/meson.build
plugins/pip/PopupWindow.vala
src/Background/BackgroundManager.vala
src/NotificationStack.vala
src/ShellClients/PanelClone.vala
src/Widgets/IconGroup.vala
src/Widgets/MultitaskingView.vala
src/Widgets/ScreenShield.vala
src/Widgets/WindowClone.vala
src/Widgets/WindowIconActor.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala
src/Widgets/WorkspaceClone.vala
src/Widgets/WorkspaceInsertThumb.vala
src/WindowManager.vala
src/Zoom.vala

Moves WindowManager.enable_animations to a separate AnimationsSettings namespace. There are a lot of objects that use wm only to get that value, in this case AnimationsSettings will simplify that. Also will help avoid passing window manager object all over the code.
Motivated by a duplicate enable_animations value in https://github.com/elementary/gala/pull/2074

Introduce AnimationsSettings

---

plugins/pip/Main.vala
plugins/pip/PopupWindow.vala
src/Background/BackgroundContainer.vala
src/Background/BackgroundManager.vala
src/DBus.vala
src/DBusAccelerator.vala
src/ShellClients/ShellClientsManager.vala
src/ShellClients/WindowPositioner.vala
src/Widgets/DwellClickTimer.vala
src/Widgets/IconGroup.vala
src/Widgets/IconGroupContainer.vala
src/Widgets/MonitorClone.vala
src/Widgets/MultitaskingView.vala
src/Widgets/PointerLocator.vala
src/Widgets/WindowClone.vala
src/Widgets/WindowCloneContainer.vala
src/Widgets/WindowIconActor.vala
src/Widgets/WindowOverview.vala
src/Widgets/WorkspaceClone.vala
src/Widgets/WorkspaceInsertThumb.vala
src/WindowManager.vala

A followup to https://github.com/elementary/gala/pull/2105

Pass Meta.Display instead of Gala.WindowManager where possible

---

src/ShellClients/PanelWindow.vala

Required for elementary/dock#307.
For positioning we should always use the full size.
If we are at the bottom we need to update the y coordinate for the custom rect so that it's plane with the screen edge otherwise we are too far up and have a gap at the bottom.

PanelWindow: Don't use custom size for positioning, correct y for bottom panels

---

data/gala.metainfo.xml.in
src/ShellClients/DelegateActor.vala
src/ShellClients/DummyActor.vala
src/ShellClients/PanelClone.vala
src/ShellClients/PanelWindow.vala
src/meson.build

Fixes https://github.com/elementary/gala/issues/2101
This is very very bad code but I just couldn't find other solution. So far I tried:
* Minimizing window
* Using `_NET_WM_STATE_HIDDEN` (which is basically minimizing AFAIK)
* Blocking X11 window events by changing its event mask
* Using XShape extension
Nothing worked. If you know any other solution please let me know.

X11: move dock window out of bounds when hidden

---

src/ShellClients/HideTracker.vala

Fixes a rare crash that occurred when a panel client was killed while an overlap update was queued.

HideTracker: Remove queued update in destructor

---

data/gala.metainfo.xml.in
src/ShellClients/HideTracker.vala

Reverts elementary/gala#2086
Taken from #2134

Revert "Fix autohide"

---

data/gala.gschema.xml
src/WindowManager.vala

Add a keyboard shortcut to launch the screenshot app.
Default is `Super` + `Print`
This is useful as an alternative to having to remember all of the shortcuts for screen, window, area and their clipboard variants or just in general if you prefer the interactive way.
As a bonus it also has the save dialog.
(As prior art: e.g. GNOME launches its interactive UI by default for the Print key, windows has snipping tool, etc.)
Needs to be added to the keyboard plug

Shortcuts: Add an interactive screenshot shortcut

---

src/WindowManager.vala

Fix cancelling workspace switch gesture

---

src/Widgets/WindowClone.vala

We now just connect to size changed signal and request reposition which we should be doing anyway. The stuff we did previously won't work on wayland because we don't have a window size and position yet when the actor becomes available so the given slot is nonsensical.
This brings no change for X neither compared to main nor to pre #2082 but fixes it for wayland.
Fixes #857

WindowClone: Fix invisible if shown while Multitasking view is open

---

src/Widgets/WindowClone.vala

This time with no major visual changes compared to main :)

WindowClone: Allocate window icon in allocate virtual

---

lib/Utils.vala
src/WorkspaceManager.vala

Fixes #2145 
Though probably not the same as #2145 (I've seen this one before the gesturepropertytransition got merged and the system version says stable) this probably also fixes #2159 
We have to do this because a window that's about to be removed still appears in the list returned by Meta.Workspace.list_windows when window_removed is emitted (at least if it's just moved and not closed).
Also fixes an inconsistency, where when in the multitasking view, a workspace would be immediately removed when the last window on it was closed but not when it was moved to another one.

WorkspaceManager: Exclude a window that's about to be removed from count

---

src/InternalUtils.vala

Hot corners still work for me without this. I have no idea why we are doing this

Cleanup `InternalUtils.set_input_area`

---

src/Widgets/PixelPicker.vala

* New copyright header
* Inline namespace
* Reduce the scope of a method
* A little cleanup of close and closed

PixelPicker: cleanup

---

src/Widgets/ScreenShield.vala
src/WindowManager.vala

Only some cleanup since we don't have to init GTK anymore, we don't have to wait anymore. 
Also include some other minor cleanups so see individual commits.
Use rebase to merge.

Move plugin stuff out of laters

---

src/Widgets/WindowClone.vala
src/Widgets/WindowCloneContainer.vala
src/Widgets/WindowOverview.vala
src/WindowManager.vala

Fix window overview

---

src/InternalUtils.vala
src/Widgets/WindowClone.vala

Tries to achieve the same as #2176 without introducing a whole class just to wait for something. Instead we add a function to internalutils that takes a callback which it will call immediately if the windowactor is already available or wait a single idle for it.

InternalUtils: Introduce wait_for_window_actor utility

---

src/Gestures/GesturePropertyTransition.vala
src/Gestures/GestureTracker.vala
src/Gestures/ScrollBackend.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WindowClone.vala
src/Widgets/WorkspaceClone.vala
src/WindowManager.vala

This currently only works when using a non touchegg backend because the touchegg backend only sends progress between 0 and 1. This means that this only works when using two fingers to switch workspaces in the multitasking view.
This puts the required infrastructure in place to allow gestures to go as far as they want also in the opposite direction than they were started in. It's then used for the workspace switch in the multitasking view while clamping it to the respective number on workspaces on either side.
It also puts a system in place that when clamping to a fractional value this last bit will feel stretched to show that in this direction the gesture is bounded.
F*xes #1057 and #1140 but only in the multitaskingview due to the aforementioned issues with touchegg.

Overshoot gestures

---

src/Gestures/Gesture.vala
src/Gestures/GestureSettings.vala
src/Gestures/GestureTracker.vala
src/Gestures/ScrollBackend.vala
src/Gestures/ToucheggBackend.vala
src/Widgets/MultitaskingView.vala
src/WindowManager.vala
src/Zoom.vala

Add information about whether a gesture will be handled. This might be used to determine whether events are supposed to be consumed. Add information about the origin of a gesture. This might be used to determine whether a gesture should be handled (e.g. only allow swipe from screen edge). Add common GestureBackend interface that all backends have to implement. Add a on_gesture_handled signal to the GestureTracker which runs if and only if true was returned in on_gesture_detected. Before it is emitted prepare_gesture_handling will be called on the backend. This will be needed for the upcoming PanBackend to avoid conflicts in event consuming.
Add a utility get_action to the GestureSettings that gets the corresponding action for a gesture. This allows to remove some duplicated code.
Split …

Gestures: Add more details and introduce on_gesture_handled

---

data/gala.gschema.xml
lib/WindowManager.vala
src/SuperScrollAction.vala
src/WindowManager.vala
src/Zoom.vala
src/meson.build

Based on #2165
Fixes https://github.com/elementary/gala/issues/815
Fixes https://github.com/elementary/gala/issues/1178
Closes https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/215
Only the last commit are my changes

Add Super+Scroll action

---

data/gala.metainfo.xml.in
plugins/pip/PopupWindow.vala

Fixes https://github.com/elementary/gala/issues/397

Prevent PiP from overlapping Wingpanel

---

data/gala.metainfo.xml.in
plugins/pip/PopupWindow.vala

Fixes https://github.com/elementary/gala/issues/2171

PiP: Fix drag and drop

---

src/InternalUtils.vala
src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/2175
Fixes https://github.com/elementary/gala/issues/2102
Closes https://github.com/elementary/gala/pull/2129
Now `InternalUtils.wait_for_window_actor` is basically the same as `Meta.Window.shown`

WindowManager: Only show notifications after their window was shown

---

src/InternalUtils.vala
src/WindowManager.vala

Fixes #2187 
Sometimes we ourselves have to hide window actors so we can't always wait for them to be visible, e.g. if we just want to create a clone for them.

Introduce InternalUtils.wait_for_window_actor_visible

---

src/Widgets/WindowClone.vala

Fixes #2170
Also introduces a little optimization to reuse window_icon_y instead of recalculating it.

WindowClone: Hide icon in overview

---

src/ScreenshotManager.vala

This invalid syntax does not seem to be affected for our build but could be a problem when `HAS_MUTTER45` is not met.

ScreenshotManager: Fix invalid syntax

---

src/Widgets/WindowClone.vala

On current main in the window overview, windows from other workspaces are hidden but reserve space because they have opacity 0.
This fixes that and adds back the nice fade animation.

WindowClone: Fix fade in overview

---

data/gala.metainfo.xml.in
src/WindowManager.vala

WindowManager/workspace switcher: Fix stacking order of moving window

---

src/Gestures/GesturePropertyTransition.vala

The transition might be interrupted by the clutter actor being destroyed leading to the callback being called which as a result might want to destroy the actor again leading to a bail out by clutter (this was the case if the nudge animation was ongoing while kill_switch_workspace was called)
Since it shouldn't be used for setting state anyway (because of how we'd like to move to interruptible gestures) which was also clarified in a comment, this should actually be the correct behavior (we don't want to cleanup any animation stuff if we're animating anew anyways).
Fixes #2145

GesturePropertyTransition: Only call done_callback if the transition finished

---

data/gala.metainfo.xml.in
src/WindowManager.vala

Fullscreening/Unfullscreening will now play the same effect as maximizing and unmaximizing (since it's pretty much just an extended version of that action I think it fits)
Also we will now move to the old ws if a window that was moved to a new ws is closed.
Fixes #1986
Fixes https://github.com/elementary/gala/issues/551
Closes #2146

Add fullscreen effect and move to old ws on close

---

src/WindowManager.vala

This issue doesn't occur in newer mutter versions

Remove fixme

---

src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/2207

Fix crash when using move to workspace gestures

---

src/WindowManager.vala

Currently when cancelling the move gesture, the window stays on the new workspace, leading to some glitches because we show it on the active one anyways because of some manual reparenting. Now we move it back to our original (active) workspace when cancelled.

WindowManager: Fix cancelling window move gesture

---

src/HotCorners/HotCornerManager.vala

If there was only one hotcorner action we would take the compatibility code path leading to our command being: `hotcorner-<position>:<actual command>`
We probably should have changed the value type here to a dict or something when we renamed the schema but that's to late now. However because of the renaming there's no need for compatibility anymore.

HotCorners: Fix custom action if there's only one

---

lib/Drawing/Canvas.vala
lib/ShadowEffect.vala
src/Background/BlurEffect.vala
src/InternalUtils.vala
src/Widgets/DwellClickTimer.vala
src/Widgets/PointerLocator.vala
src/Widgets/WindowCloneContainer.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala
src/Widgets/WorkspaceClone.vala
src/WindowManager.vala
src/Zoom.vala

Fixes #2217 
Use rebase to merge

Remove Clutter.get_default_backend usage

---

src/Gestures/GestureTracker.vala
src/ShellClients/PanelClone.vala

Split out from #2150 for easier review.
This introduces some inconsistencies when opening multitasking view and switching workspaces but these will be fixed properly by the follow ups from #2150.
The changes here include using the translation-y property of the window actor to hide it instead of making it invisible and animating a clone. Also included is the use of the GesturePropertyTransition for the actual animation and the related introduction of GestureTrackers. This is preparation for moving all panel hiding stuff to the shell clients (instead of the multitasking view doing its own thing with additional clones) as well as one to one touch gestures for showing the dock.

ShellClients: Use translation y instead of clone and use gesturetransition for animation

---

src/InternalUtils.vala
src/ShellClients/HideTracker.vala
src/ShellClients/PanelClone.vala
src/ShellClients/PanelWindow.vala
src/ShellClients/ShellClientsManager.vala
src/Widgets/MultitaskingView.vala
src/WindowManager.vala

Since moving the panel hiding from the multitasking view completely to the shell clients and introducing a shell group are bigger changes, I think they probably should be separated which is what this PR does.
It still includes the new version of #2192 but now only introduces the shell group which is (taken from the code comment):
> The group that contains all WindowActors that make shell elements, that is all windows reported as 
ShellClientsManager.is_positioned_window and notifications, as well as manually added elements.
It will (eventually) never be hidden by other components and is always on top of everything. Therefore elements are
responsible themselves for hiding depending on the state we are currently in (e.g. normal desktop, open multitasking view, fullscreen, etc.).
This will …

Introduce a shell group

---

src/ShellClients/HideTracker.vala

Fixes #2267 
Explanation from the code comment:
> The timeouts hold refs on us so we stay connected to signal handlers that might
access the panel which was already freed. To prevent that make sure we reset
the timeouts so that we get freed immediately

HideTracker: Disconnect timeouts on unmanaging

---

src/WorkspaceManager.vala

Tries to do the same as #2243.
It also fixes some warnings `g_object_notify: assertion 'G_IS_OBJECT (object)' failed`.
The reason from the code comment:
> We might be here because of a signal emition from the ws machinery (e.g. workspace.window_removed).
> Often the function emitting the signal doesn't take a ref on the ws so if we remove it right
> away it will be freed. But because the function often accesses it after the singal emition this leads
> to warnings and in some cases a crash.
Might fix https://github.com/elementary/gala/issues/2242, https://github.com/elementary/gala/issues/2227, https://github.com/elementary/gala/issues/2232.
Fixes the crash described in #2258

WorkspaceManager: Fix crash on workspace removed

---

src/Gestures/ToucheggBackend.vala

Reason behind this (from #2258):
Ok I did some more investigation. Turns out that the reason is that in our toucheggbackend we receive events in a different thread and send them via idle to the main thread. So far so good. However we use Priority.DEFAULT_IDLE (we don't set anything) which might cause them to be stuck behind other more important events. This is the case when we do update_hover_widgets in the window clone because there they get animated via set_easing etc. which seemingly blocks lower priority events. This sometimes causes a delay which seems like a lag.

ToucheggBackend: Use Priority.DEFAULT for sending events to the main thread

---

src/WorkspaceManager.vala

This should hopefully work now :crossed_fingers:
Fixes elementary/dock#389

WorkspaceManager: Fix dynamic workspaces

---

src/WorkspaceManager.vala

Another day another fix for the workspace manager. Here's to hoping that it doesn't make it worse once again.
When cleaning we only want to remove workspaces that we aren't on. Currently we can end up with no empty workspace at the end and sometimes crashes.
Cherry picked from #2291.

WorkspaceManager/cleanup: Fix crash

---

daemon/DBus.vala
lib/Plugin.vala
lib/WindowManager.vala
src/PluginManager.vala
src/WindowManager.vala

- Don't expose multitasking view to the library as no one uses it
- Don't support overriding multitasking view via plugin because we rely on it for desktop switch now
- 'Workspace view' -> 'Multitasking view'

Simplify multitasking view type

---

src/ShellClients/HideTracker.vala

When the barrier was triggered and you wouldn't ever hover the dock there wouldn't be a new update so the dock would stay visible. So make sure to schedule an update on barrier trigger.
Fixes #2276
Fixes elementary/dock#357

HideTracker: Fix not hiding when barrier triggered without hovering

---

src/Widgets/MultitaskingView/MultitaskingView.vala

Two fixes for the multitasking view.
The first commit fixes #2297 where we would push modal twice leading to one of the grabs never being released.
The second commit fixes an issue where you could initiate a drag and drop on window clones while
the workspace switch animation finished which looks very strange.

Multitasking view fixes

---

src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/898

Switch/Move to ws shortcuts: if ws doesn't exist, switch to last instead

---

src/WorkspaceManager.vala

Do it like GNOME does it (https://github.com/GNOME/gnome-shell/blob/35beb976b71304c86b1a7e1c75ed5b0912908350/js/ui/windowManager.js#L229) with some minor modifications
Gets rid of a bunch of complexity and should finally fix the crashes related to this :crossed_fingers: 
Should be ready now.
A new behavior is that while in the multitasking view if we close all windows on the second to last ws it just becomes the last instead of switching to the one to the left which I think is the more expected behavior. The icongroup icon doesn't get the plus there but they will be removed soon anyways :)

Rewrite WorkspaceManager

---

src/Gestures/ScrollBackend.vala
src/Widgets/MultitaskingView/WindowClone.vala

Get rid of the weirdness in commit_progress and the required additional check in update_progress.
A scroll action will now only trigger if the scroll direction matches its orientation.
This now in theory also supports disabled animations but if multiple windows are open it will pretty much close all since they probably rearrange before you stop scrolling. Currently it's still enabled but we can disable it.
Also fixes runtime warnings about non existing objects.
Also the additional check around update_hover_widgets was removed. Idk why it was added but if we need it we should also update on switching workspaces because the close button and windowtitle appear when switching workspaces on the desktop which looks weird.

Respect orientation in scroll backend

---

src/DesktopIntegration.vala
src/Widgets/MultitaskingView/MultitaskingView.vala

First commit adds a dbus method to reorder workspaces required for elementary/dock#392
Second commit fixes a small issue where if the active workspace was reordered the multitasking view was still at the outdated active index which now is a different workspace.

Reorder workspaces

---

src/DesktopIntegration.vala

This signal doesn't get emitted currently. However we need it for the background portal implementation where we use it to notify the portal about apps that don't have windows anymore.
Probably fixes elementary/portals#97

DesktopIntegration: Fix no emission of the running_applications_changed signal

---

lib/Constants.vala
src/Gestures/ScrollBackend.vala
src/Widgets/MultitaskingView/MonitorClone.vala
src/Widgets/MultitaskingView/MultitaskingView.vala
src/Widgets/MultitaskingView/WindowClone.vala
src/Widgets/MultitaskingView/WindowCloneContainer.vala
src/Widgets/MultitaskingView/WorkspaceClone.vala
src/Widgets/WindowOverview.vala

Fixes https://github.com/elementary/gala/issues/2199
https://github.com/user-attachments/assets/8996a666-a80a-4dde-9246-df8d55198783

Multitasking view: swipe up to close window

---

lib/ShadowEffect.vala
plugins/pip/PopupWindow.vala
src/Widgets/MultitaskingView/IconGroup.vala
src/Widgets/MultitaskingView/WindowClone.vala
src/Widgets/MultitaskingView/WorkspaceClone.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala

No functional changes
1. Rename `scale_factor` into `monitor_scale` since it better represents what this field really means
2. Require to set `monitor_scale` on construct

ShadowEffect: cleanup scale factor

---

src/ScreenSaverManager.vala
src/Widgets/SessionLocker.vala
src/WindowManager.vala
src/meson.build

IMHO 'SessionLocker' better represents what this class does. And I plan to use name 'ScreenShield' as a general component that can block user from interacting with the stage, which will be useful for https://github.com/elementary/gala/pull/1999 and https://github.com/elementary/gala/issues/836

ScreenShield -> SessionLocker

---

src/Widgets/MultitaskingView/WindowClone.vala

Currently if you hover over close button in the multitasking view, it will disappear. This patch fixes this bug

WindowClone: fix close button

---

src/WindowManager.vala

In Wayland (xdg-shell) both menus and tooltips have window type of MENU (xdg_popup), so we cannot have different effects for them. Scaling effect looks weird on tooltips, so I propose removing it

Remove scaling effect for menus

---

src/Widgets/MultitaskingView/MultitaskingView.vala
src/Widgets/MultitaskingView/WorkspaceClone.vala

I'd like to move workspace setup to the workspacerow so the less signals we have to connect the better :)

WorkspaceClone: Activate workspace here

---

src/ScreenshotManager.vala

Fixes https://github.com/elementary/gala/issues/823

Check for redacted font

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala

Should fix #2308 
Closes #2360 
Explanation (kinda long im sorry):
The clutter stage holds an unowned reference on the actor that has key focus. That actor is responsible for unsetting the key focus if it has it and 
- is unmapped or
- is disposed
For that it has to be in the actor hierarchy in order to reach the stage via its parents which is usually a given because the actor is unmapped if it would be removed from the scene and unsets the keyfocus then.
However in our case the actor has already been unmapped when the switcher closed. When we now open it again and call `select_icon (null)` we first set the gesture controller progress to 0 which might end up setting the first icon as the current icon if it's not currently the current icon. This will also set it as the key focus actor for …

WindowSwitcher: Fix crash

---

data/gala.metainfo.xml.in

#2308 is not present in the stable gala release, it appeared during transition to GestureContoller

Remove #2308 from metainfo

---

src/Gestures/GestureController.vala
src/Gestures/RootTarget.vala
src/Gestures/ScrollBackend.vala
src/ShellClients/PanelWindow.vala
src/Widgets/MultitaskingView/MultitaskingView.vala
src/Widgets/MultitaskingView/WindowClone.vala
src/Widgets/WindowOverview.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala
src/Zoom.vala
src/meson.build

We are leaking WindowClones since #2327. This is because the GestureController holds a strong reference on the target which means in our case that the windowclone holds a strong ref on the controller which holds a strong ref on the window clone => ref cycle. That is for example also why we set it to null in the panelwindow once it unmanages https://github.com/elementary/gala/blob/a9868810ffacb35001647e63eafc4091cabd6329/src/ShellClients/PanelWindow.vala#L54
While we could easily work around this I admit for how we currently use it the ownership model of gesturecontrollers is not really intuitive.
There are multiple solutions to this problem:
- We could just do the same as in panel window but we don't exactly know the lifetime of a windowclone (it can move to other ws, unmanage, etc.) and …

Remodel GestureController lifetimes

---

src/KeyboardManager.vala
src/WindowManager.vala

- Don't make KeyboardManager object static
- Don't check for gsettings schema
- Move 'switch-input-source' keybindings here

KeyboardManager: cleanup

---

data/gala.metainfo.xml.in
src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/2172
Fixes https://github.com/elementary/gala/issues/2366
Some windows don't expect there to be a destroy effect for menus and they close their windows before the we call `destroy_completed`. I suppose if we still need this effect, we should implement it in Granite.

Remove destroy effect for menus

---

lib/ShadowEffect.vala

Fixes https://github.com/elementary/gala/issues/2380
Fixes https://github.com/elementary/gala/issues/2357

ShadowEffect: fix scale

---

lib/Utils.vala

Fixes https://github.com/orgs/elementary/discussions/766
Currently when we unset x11 pass through, we set window region to its previous size, however panels can change their sizes and the part that wasn't there (e.g. wingpanel popovers) will not be clickable. This branch correctly unsets the window region and avoids that bug.

Correctly unset x11 pass through

---

data/gala.metainfo.xml.in
lib/Utils.vala
meson.build
src/ShellClients/ShellClientsManager.vala
src/ShellClients/ShellWindow.vala
vapi/xfixes-4.0.vapi

Currently in gala 8.2.1, if you open multitasking view on X11 and close it, the dock clickable area will be a lot bigger then its visible part.
Unseting window shape region entirely doesn't work for our Dock since its window size is a lot bigger than its visible part. This branch introduces `restore-previous-region` argument for mutter hints. If it's set, we restore previous region (dock needs this), if not, unset region (wingpanel needs this).

Add support for restoring previous region

---

src/Gestures/GestureController.vala

Fixes #2409 
Once one finger gets lifted we switch from touch egg backend to scroll backend which would emit end and start signals which would cause a hide and show on the multitasking view which in turn would interrupt and restart the scroll gesture but not emit a end because of a wrong order. We can solve all these problems if we just don't emit start and end when the gesture gets interrupted while still going. This also is a small performance improvement because we don't go hidden shown everytime which saves us a bunch of recalculations.
Also don't allow a new gesture to start while one is already going.
(thanks @zeebok for the reproducer)

GestureController: Handle gesture interruption transparently

---

src/Widgets/MultitaskingView/MultitaskingView.vala

Fixes https://github.com/elementary/gala/issues/2230
I confirmed the fix on virtual machine

MultitaskingView: Reload blurred bg when updating monitors

---

src/ShellClients/ShellWindow.vala

Fixes https://github.com/elementary/dock/issues/425
Closes #2418 
There are things in the shell group that can be on secondary monitors (most notably freely movable transient windows like the connect to hidden network window). Also sometime soon the monitor labels should go there so they will need to be on secondary monitors. So instead of clipping the whole group only clip the respective actors.

ShellWindow: Clip window actor when applying translations

---

src/ScreenshotManager.vala

https://github.com/elementary/notifications/issues/237 is not resolved and therefore this looks ugly on some locales

Remove 'Open in Photo Viewer' action from screenshot notification

---

src/WindowStateSaver.vala

This is the proper way to create SQL queries. Also make sure to not save unmaped windows.

WindowStateSaver: Avoid sql injections by using sqlite statements

---

src/ShellClients/PanelWindow.vala
src/ShellClients/PositionedWindow.vala
src/ShellClients/ShellWindow.vala

Use real dock size for hide animation
https://github.com/user-attachments/assets/480d5acf-c251-4000-8543-343041fe0877
https://github.com/user-attachments/assets/cc326232-ffd7-44a1-8e67-b04dea6410a3

Improve dock hide animation

---

src/ShellClients/ShellWindow.vala

Shell windows are in the shell group and are therefore above fullscreen windows. They can also be visible when a window is fullscreen via the new reveal feature. Also the animation plays when a window is already full screen. So we want to make sure to disable unredirection when we are visible so that we are actually visible.
Fixes an issue where when you are in a fullscreen firefox playing a video or in videos playing a video you wouldn't be able to reveal the wingpanel.

ShellWindow: Disable unredirection when visible

---

lib/Utils.vala
plugins/pip/PopupWindow.vala
src/InternalUtils.vala
src/WindowManager.vala
src/WindowTracker.vala

It is duplicated in PiP plugin, so move it into library to fix this

Move `get_window_is_normal` to library

---

src/WindowManager.vala

Currently windows can't be pushed to the bottom in Wayland, so this code is basically unused

Remove custom animation for bottom stack windows

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala
src/Widgets/WindowSwitcher/WindowSwitcherIcon.vala

WindowSwitcher:
- Remove one-time method
- Use constant from AnimationDuration
- Other minor cleanups
WindowSwitcherIcon:
- Move icon size constant here
- Use Clutter.BinLayout instead of constraint
- Don't manually set size, rely on layout manager to calculate it for us

Cleanup WindowSwitcher

---

.github/workflows/main.yml

Not sure if we want to support this, but I don't see reasons why not. Makes fixing https://github.com/elementary/gala/issues/2368 easier since we still 'support' Mutter 45

Add OpenSuse Leap CI

---

src/BackgroundBlurEffect.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala
src/meson.build
vapi/mutter-clutter.vapi
vapi/mutter-cogl-14.vapi
vapi/mutter-cogl.vapi

New clean branch that should be easier to review
Window switcher is used as an example of how this effect can be used because Danielle showed some interest in blurring it: https://github.com/elementary/granite/pull/747#issuecomment-2704200141
Can be rebase merged

WindowSwitcher: blur background

---

data/shaders/colorblindness-correction.vert
data/shaders/monochrome.vert
src/ColorFilters/ColorblindnessCorrectionEffect.vala
src/ColorFilters/FilterManager.vala
src/ColorFilters/MonochromeEffect.vala
src/ScreenshotManager.vala
src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/1680

Pause filters before taking screenshots

---

lib/Gestures/Gesture.vala
src/ShellClients/PanelWindow.vala
src/ShellClients/ShellWindow.vala
src/Widgets/MultitaskingView/WindowClone.vala

Replaces our DOCK and CLOSE_WINDOW gesture actions with CUSTOM. This allows us to use this action in plugins (e.g. for hiding PiP). This change shouldn't affect anything since users of DOCK and CLOSE_WINDOW are self-contained and don't have complicated target hierarchy.

Introduce GestureAction.CUSTOM

---

lib/Text.vala
lib/meson.build
src/Widgets/MultitaskingView/Tooltip.vala
src/Widgets/WindowSwitcher/WindowSwitcher.vala

Clutter.Text object that automatically changes font-name to the system one. You can test this branch by enabling "Dyslexia-friendly font" in the System Settings -> Desktop -> Text.

Introduce Gala.Text

---

meson.build
src/DaemonManager.vala
src/DesktopIntegration.vala
src/KeyboardManager.vala
src/ShellClients/HideTracker.vala
src/ShellClients/ManagedClient.vala
src/ShellClients/NotificationsClient.vala
src/ShellClients/ShellClientsManager.vala
src/Widgets/SessionLocker.vala
src/WindowManager.vala
vapi/Clutter-17.metadata
vapi/Cogl-17-custom.vala
vapi/Cogl-17.metadata
vapi/Meta-17.metadata
vapi/Mtk-17.metadata
vapi/libmutter-17.deps
vapi/libmutter-17.vapi
vapi/libmutter.vapi
vapi/meson.build
vapi/mutter-clutter-17.deps
vapi/mutter-clutter-17.vapi
vapi/mutter-clutter.vapi
vapi/mutter-cogl-14.vapi
vapi/mutter-cogl-17.deps
vapi/mutter-cogl-17.vapi
vapi/mutter-mtk-13.vapi
vapi/mutter-mtk-17.vapi

Amongst another news, Mutter 49 allows us to apply "Dock" capabilities to any wayland client and thus allows the Dock and Wingpanel to be launched by systemd instead of Gala :tada: 
Closes #2475

Add support for Mutter 49

---

data/gala@wayland.service.in

Fixes https://github.com/elementary/gala/issues/2489
The solution is taken from https://github.com/flatpak/flatpak/issues/3880#issuecomment-1265349004

Cleanup Wayland sockets on logout

---

protocol/pantheon-desktop-shell-v1.xml
protocol/pantheon-desktop-shell.vapi
src/BackgroundBlurEffect.vala
src/BlurManager.vala
src/PantheonShell.vala
src/WindowManager.vala
src/meson.build

Fixes https://github.com/elementary/gala/issues/1998
To do:

Add Blur API

---

src/Widgets/MultitaskingView/WindowClone.vala

Fixes https://github.com/elementary/gala/issues/2444

WindowClone: fix drag animation with multiple monitors

---

lib/Drawing/StyleManager.vala
src/Background/BackgroundCache.vala
src/PluginManager.vala
src/Widgets/MultitaskingView/StaticWindowContainer.vala
src/WindowDragProvider.vala

... and remove redundant constructor of BackgroundCache

Use GLib.Once for singletons
