data/org.pantheon.desktop.gala.gschema.xml.in

Fixes #42. Feel free to discuss the key.

Change PIP hotkey

---

data/gala-multitaskingview.desktop.in

Add OnlyShowIn=Pantheon to multitasking .desktop

---

data/org.pantheon.desktop.gala.gschema.xml.in
src/Settings.vala
src/Widgets/WindowSwitcher.vala

fixes #52.
Darkens the background when entering the window switcher with Alt+Tab. This has to be tested by someone with multiple monitors.

Dim the background while alt-tabbing

---

src/Widgets/WorkspaceInsertThumb.vala

Fix: Icons in WorkspaceInsert being offset

---

lib/Utils.vala
lib/WindowIcon.vala
src/InternalUtils.vala
src/Widgets/WindowSwitcher.vala

Scale the dock for HiDPI during Alt+Tab switching

---

meson.build

Bump requirement to match upstream and add dummy bindings

meson: Fix build with libmutter-2

---

src/WindowManager.vala

Fixes #8.
Implements `show_tile_preview` and `hide_tile_preview` for showing tile previews when window is about to be tiled into a certain area.

Show tile previews

---

HACKING

A lot of the links were outdated, as well the file was based around bzr and Launchpad.

Update HACKING file

---

src/Widgets/IconGroup.vala
src/Widgets/IconGroupContainer.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WindowClone.vala
src/Widgets/WindowIconActor.vala
src/Widgets/WorkspaceClone.vala
src/Widgets/WorkspaceInsertThumb.vala

Fixes #101 
Most of this work was done in a branch by @donadigo , but I'm opening a PR for visibility. I've fixed a couple of bits that looked wrong after testing on a HiDPI display. Still needs some in depth looking at compared to a non-HiDPI display though. I can't tell if some of the animations look a bit funky when you're dropping them on a new workspace or if they were always like that.

HiDPI Workspace Switcher

---

src/WindowManager.vala

Looks like the size_change isn't called when switching directly between tile positions using the keyboard. Possibly because the size isn't changed. But position_changed is called. 
Fixes:  #341 
Possibly also fixes: #305

Tile switching fix

---

src/Widgets/WindowSwitcher.vala

Update the scale factor when updating the dock

---

src/WindowManager.vala

Fix minimize animation in HiDPI monitor (#164)

---

src/WindowManager.vala

Fix fullscreen a maximized chromium window on secondary screen

---

lib/ActivatableComponent.vala
lib/Constants.vala
lib/Plugin.vala
lib/Utils.vala
lib/WindowIcon.vala
lib/WindowManager.vala

Fixed any errors/warnings that came up from running vala-lint.
Assuming you have [vala-lint](https://github.com/elementary/vala-lint) installed locally:
```sh
io.elementary.vala-lint -d lib
```
Assuming you have docker installed locally:
```sh
docker run -v "$PWD":/app valalang/lint io.elementary.vala-lint -d lib
```

Lint lib directory with vala-lint

---

plugins/notify/NotificationStack.vala

Fix notifications position after DPI switch

---

data/org.pantheon.desktop.gala.gschema.xml.in
src/InternalUtils.vala

Plus a kinda related fix.
Fixes https://github.com/elementary/gala/issues/391

Make legacy shadows more subtle

---

plugins/maskcorners/Main.vala
plugins/maskcorners/Settings.vala
plugins/notify/ConfirmationNotification.vala
plugins/notify/Main.vala
plugins/notify/NormalNotification.vala
plugins/notify/Notification.vala
plugins/notify/NotificationStack.vala
plugins/notify/NotifyServer.vala
plugins/notify/NotifySettings.vala
plugins/pip/Main.vala
plugins/pip/MoveAction.vala
plugins/pip/PopupWindow.vala
plugins/pip/SelectionArea.vala
plugins/pip/ShadowEffect.vala
plugins/template/Main.vala
plugins/zoom/Main.vala

move brackets to follow vala-lint style requirements.
To verify: 
```
docker run -v "$PWD":/app valalang/lint:latest io.elementary.vala-lint -d plugins
```

lint brackets in plugins directory

---

plugins/notify/Main.vala
src/NotificationStack.vala
src/WindowManager.vala

The previous modification didn't took the API changes from 3.30, this commit resolves this issue.

notify: Make it build with Mutter >= 3.30

---

src/WindowManager.vala

This triggered crashes on my end

WindowManager: Ensure that we have a valid WindowActor before using it

---

debian/gala.install

Required to fix the build after #726

deb-packaging: Install daemon autostart

---

vapi/mutter-clutter.vapi

And a few straightforward changes from latest vapi generation

mutter-clutter: make all KEY constants unsigned integers

---

src/DBusAccelerator.vala

Similar to https://github.com/elementary/greeter/pull/421

DBusAccelerator: Fix grab_accelerator argument order

---

data/gala.appdata.xml.in
meson.build

diff: https://github.com/elementary/gala/compare/3.3.0...master
**Changelog:**
<p>Improvements:</p>
<ul>
<li>Fix crash when changing workspaces while a transient window is opening</li>
<li>Updated translations</li>
</ul>

Release 3.3.1

---

data/gala.appdata.xml.in
meson.build

Fixes a pretty nasty disappearing window bug.

Release 3.3.2

---

src/ScreenshotManager.vala
src/Widgets/PixelPicker.vala
src/meson.build

Fixes #796
Fixes #612 
I haven't put any conditional compiles in since there's no harm in this being in bionic either.

Implement color picker interface

---

data/20_elementary.pantheon.wm.gschema.override

Fixes https://github.com/elementary/gala/issues/758

override: Update the mutter schemas

---

data/gala.gschema.xml

So we don't accidentally hose your session if you have this plugin still

GSchema: revert removing notification schema

---

plugins/zoom/Main.vala

Add feedback if zooming out is not possible

---

src/Widgets/PointerLocator.vala

Instead of constructing a new `Cairo.ImageSurface` on each paint call, re-use and clear the old one.

PointerLocator: Re-use surface

---

src/InternalUtils.vala
src/Widgets/DwellClickTimer.vala
src/Widgets/PointerLocator.vala

Set accent color in DwellClick and PointerLocator

---

src/meson.build

Fix https://github.com/elementary/gala/issues/915

build: fix build with mutter less than 3.36

---

src/NotificationStack.vala
src/ScreenshotManager.vala
src/Widgets/IconGroup.vala
src/Widgets/WindowClone.vala
src/Widgets/WindowIconActor.vala
src/Widgets/WindowOverview.vala
src/Widgets/WindowSwitcher.vala
src/Widgets/WorkspaceClone.vala
src/Widgets/WorkspaceInsertThumb.vala
src/WindowManager.vala

Some files do not follow the [recommend elementary code style for initializing objects with properties](https://docs.elementary.io/develop/writing-apps/code-style#initialize-objects-with-properites).
I wrote a small Python script which finds all these cases and replaces them with the recommended code style. It could also be used for other repos.
`python codestyle.py <path/to/file.vala>` or `python codestyle.py <path/to/repo>`
<details><summary>codestyle.py</summary>
<p>
```python
from operator import itemgetter
from pathlib import Path
import regex
pattern = regex.compile(
r"(?P<space>[ \t]*)(?P<init>[\w,.]+ (?P<name>\w+) = new [\w,.]+ \([^;]+);\n"
r"(?:[ \t]*(?P=name).(?P<props>\w+\s?=\s?[^;]+);\n)+"
)
def replace(match):
capturesdict = match.capturesdict()
(space,), (init,), props = …
```

Code Style: Initialize Objects with Properties

---

src/WindowManager.vala

Fix https://github.com/elementary/gala/issues/991

Fix #991: Add a gap between workspaces when swiping/navigating

---

src/WindowManager.vala

Fix https://github.com/elementary/gala/issues/926

Background disappears while switching workspaces with multiple displays

---

src/Widgets/MultitaskingView.vala
src/Widgets/WorkspaceClone.vala
src/WindowManager.vala

A fix for this animation issue https://github.com/elementary/gala/issues/997

Workspaces in multitasking view should not animate as if they are stacked

---

plugins/maskcorners/Main.vala

View with hide whitespace changes
* No `using` namespace
* Explicit scope
* brackets

Plugins/MaskCorners: Code style cleanups

---

src/WindowManager.vala

Fix https://github.com/elementary/gala/issues/509

Fix #509: Follow animation settings in the workspace nudge animation

---

src/InternalUtils.vala
src/Widgets/MultitaskingView.vala
src/WindowManager.vala

Fix https://github.com/elementary/gala/issues/1032

Fix #1032: Workspace doesn't bump hard enough when swiping at the end

---

src/InternalUtils.vala

InternalUtils: manually build label widget path

---

src/InternalUtils.vala

And explicit scope for a few functions while we're here

InternalUtils: Remove unused constants

---

src/Widgets/WindowClone.vala

Round the corners of the actor used to highlight the selected window
in the multitasking view when keyboard navigation is used.

multitasking-view: Keyboard navigation rounded highlight

---

src/Widgets/WindowClone.vala

Fix https://github.com/elementary/gala/issues/1131

Multitasking view: Keyboard focus highlight should use accent color

---

README.md

Update the docs to match the required versions

README: Update dependency versions

---

src/Widgets/WindowClone.vala

The multitasking view has a few issues when the scaling factor is changed.
This PR fixes them. Easier to review commit by commit.

Multitasking view: fix scaling factor bugs

---

data/gala.appdata.xml.in
meson.build

Not a huge release, but I've had some app developers already encountering this issue since Gtk.Dialog uses SSD now

Release 6.0.1

---

src/MediaFeedback.vala

Simply send notifications if the daemon is currently running.

MediaFeedback: Simplify the handling of the notification bus

---

src/Widgets/Tooltip.vala

Use built in render function from Gtk.StyleContext

Tooltip: render from stylecontext

---

data/gala.appdata.xml.in
meson.build

Release 6.2.1

---

src/Main.vala

Handle signal to close Gala gracefully on Mutter 3.41

---

src/Widgets/IconGroupContainer.vala

Gets read of a terminal error I was getting

IconGroupContainer: add null check to get_next_sibling

---

src/WindowManager.vala

I'm still having issues where sometimes windows don't undim, but it looks like maybe this really fixes it this time for real, final final.psd

WindowManager: don't type check when undim

---

.github/workflows/main.yml
HACKING
data/gala.gschema.xml
lib/WindowManager.vala
plugins/template/Main.vala
plugins/template/README
src/Background/BackgroundSource.vala
src/DBus.vala
src/NotificationStack.vala
src/WindowManager.vala
src/WorkspaceManager.vala

Found via `codespell -q 3 -S *.po`

Fix various typos

---

src/WindowManager.vala

* Makes actions match the question being asked
* Much shorter button labels
* Explains the timeout

WindowManager: Rewrite display settings labels

---

meson.build
plugins/pip/PopupWindow.vala
src/WindowManager.vala
vapi/Clutter-10.metadata
vapi/Meta-10.metadata
vapi/libmutter.vapi
vapi/mutter-clutter.vapi
vapi/mutter-cogl-6.vapi

Update bindings to latest Mutter

---

debian/control

Also remove dependency on libclutter-dev as it has long been included in libmutter.

Add dependency on libmutter-10-dev

---

data/gala.appdata.xml.in
meson.build

Release 6.3.1

---

src/ScreenshotManager.vala
src/Widgets/DwellClickTimer.vala
src/Widgets/PointerLocator.vala
vapi/libmutter.vapi

Fixes #1403
This allows for a better transition handling than setting properties.

Update to latest mutter bindings and use Transition objects

---

lib/WindowManager.vala
plugins/pip/SelectionArea.vala
src/Widgets/MultitaskingView.vala
src/Widgets/PixelPicker.vala
src/Widgets/ScreenShield.vala
src/Widgets/SelectionArea.vala
src/Widgets/WindowOverview.vala
src/Widgets/WindowSwitcher.vala
src/WindowManager.vala
vapi/mutter-clutter.vapi

This is the new way of grabbing the keyboard input.

Use Clutter.Grab with Mutter 42

---

src/Widgets/WindowSwitcher.vala

Fixes #1396 
Thanks @tintou for your recent merges, made this fix easy, assuming it's reviewed and looks good!

Fix window switcher not focussing selected window upon release key.

---

src/Widgets/WorkspaceClone.vala

Fixes #1356 
AFAICT, Cogl.Framebuffer's clip functions only clip things outside of the defined rectangle, not inside. So, instead use Cairo to draw a stroke.
It looks like the black stroke was leftover from before we drew the shadow with `shadow_effect` maybe? It doesn't appear to be necessary anymore

WorkspaceClone: draw stroke with Cairo

---

src/WindowManager.vala

WindowManager: save/restore easing on workspace switch

---

src/DBusAccelerator.vala

Allows to keep in memory the intend of an accelerator.

DBusAccelerator: Use the same version as in the greeter

---

po/POTFILES

So that translators can add translations for the texts in the force quit dialog:
https://github.com/elementary/gala/blob/5f0fcc683f9b0b6b233d1182a33ed429825684c0/src/Dialogs.vala#L152-L159

POTFILES: Add src/Dialogs.vala

---

data/gala.gschema.xml
src/Background/BackgroundManager.vala

Resolves #966
Settings for this branch: elementary/switchboard-plug-pantheon-shell#336
Not sure if it's ok to create a new schema path for one property, but it can be moved to existing one if you so desire

Option to dim wallpapers when dark style is active

---

src/Widgets/WindowClone.vala

We have some failures in the logs.

WindowClone: Make sure that the clone is setup before using it

---

lib/App.vala
lib/AppCache.vala
lib/AppSystem.vala
lib/meson.build
meson.build
src/DBus.vala
src/DesktopIntegration.vala
src/WindowManager.vala
src/WindowTracker.vala
src/meson.build

This allows us to completely replace libbamf in some specific cases (like system shell elements).
This PR is only opened for showing the intention, it's far from even starting to work.

App: Implement Applications Management

---

data/gala.appdata.xml.in
meson.build

Release 6.3.2

---

plugins/pip/PopupWindow.vala

PiP: Fix window resizing on Mutter 42

---

src/NotificationStack.vala

As reported in elementary/notifications#139 and elementary/gala#1456, the compositor can sometimes crash when a notification is received. This can be potentially catastrophic: the compositor does get restarted by the session daemon, but if the crash occurs twice within one minute, the session is made unusable, and all unsaved changes will be lost unless you know the magic incantations.
While I'm not yet 100% sure whether this is an upstream issue or something we are doing wrong on our side (see https://github.com/elementary/notifications/issues/139#issuecomment-1325614603 and the following comment) I do see a lot of value in including this workaround, as a stop-gap solution.
There's still a little bit of bugginess if a notification is received during a workspace switch; they may display …

Work around crash when receiving notifications

---

src/ShadowEffect.vala

Seems to stop shadows from lingering around. Fixes #1443, hopefully. Have only tested this for a couple minutes.

ShadowEffect: let Clutter know the shadow's size

---

src/Zoom.vala

Fixes #1484.
Review with "Hide whitespace".
While we're here:
* Put Gala namespace inline
* Update copyright header

Fix quick zooming

---

src/Widgets/MultitaskingView.vala

Fix workspace switching animation in multitasking view

---

data/gala.appdata.xml.in
meson.build

GranPC has some other branches waiting for review, if we can get to more that would be awesome. But this already contains a lot of performance fixes and crash fixes so really would like to get this in

Release 7.0.0

---

src/Widgets/MultitaskingView.vala

Allow KeyBindingAction.NONE in Multitasking View

---

po/nl.po
src/Widgets/IconGroup.vala

Fix IconGroup close button animation

---

src/Widgets/MultitaskingView.vala

Allow super key in multitasking view only when super key toggles it
Resolves #1483

Better super key filter in multitasking view

---

plugins/pip/PopupWindow.vala
plugins/pip/ShadowEffect.vala
src/ShadowEffect.vala
src/Widgets/MultitaskingView.vala

Review with "Hide whitespace"
* Inline namespaces
* Explicit Clutter namespace
* Update copyrights
* Copy new ShadowEffect class to PIP

ShadowEffect: inline namespace, copy to PIP

---

src/Widgets/WindowClone.vala

Fixes WindowClone shadow issues on HiDPI

WindowClone: Remove custom WindowShadowEffect class

---

src/Widgets/WindowClone.vala

* Fix code style issues
* Remove unused/duplicate variables
* Explicit `private`
* Use constants as return value where possible

WindowClone: Cleanup

---

plugins/pip/ShadowEffect.vala
src/InternalUtils.vala
src/Widgets/IconGroup.vala
src/Widgets/IconGroupContainer.vala
src/Widgets/MonitorClone.vala
src/Widgets/MultitaskingView.vala
src/Widgets/SafeWindowClone.vala
src/Widgets/WindowCloneContainer.vala
src/Widgets/WindowIconActor.vala
src/Widgets/WindowOverview.vala
src/Widgets/WorkspaceClone.vala
src/WorkspaceManager.vala

Explicit Clutter and Meta namespaces

---

data/gala.appdata.xml.in
plugins/pip/PopupWindow.vala

PIP: Fix log spam

---

src/Widgets/MultitaskingView.vala
src/Widgets/WindowClone.vala

- Fix weird icon animation when opening multitasking view
- Animate maximized windows shadow opacity with gestures

Fix multitasking view animations

---

lib/DragDropAction.vala
src/Widgets/WindowOverview.vala

WindowOverview: Cleanup

---

plugins/pip/PopupWindow.vala

PiP: Respect animations key

---

lib/DragDropAction.vala

Reverts elementary/gala#1506
elementary/gala#1506 introduces #1552

Revert "Draft: Fix PiP window being undraggable"

---

src/Widgets/WindowSwitcher.vala

Select a window on button release instead of button press.

WindowSwitcher: Select a window on button release

---

data/gala.appdata.xml.in
src/KeyboardManager.vala

Resolves #1566
While we're here:
* Update copyright header
* Inline workspace
* Add https://github.com/elementary/gala/issues/1059 to appdata

Set keyboard layout using `lock_layout_group`

---

src/Widgets/WindowClone.vala

Addresses #1136
ActiveShape.allocate  while animating:
0.002864 -> 0.000057 seconds (~50 times faster)

WindowClone: optimize ActiveShape

---

data/gala.appdata.xml.in
src/WindowManager.vala

Check if window can maximize before performing action

---

data/gala.appdata.xml.in
lib/DragDropAction.vala
src/Widgets/IconGroup.vala

DnD: Don't disable reactivity

---

src/Widgets/DwellClickTimer.vala

Similar to #1606 
Supports per-monitor, non-integer scale factors for this widget.
Reduces the diff of #1570

DwellClickTimer: Support non-integer, monitor specific scales

---

data/gala.gschema.xml
src/InternalUtils.vala
src/WindowManager.vala

Fixes #1534
Closes #511
Not sure what Meta.ShadowFactory does, but removing it solves the issue. Gnome Shell doesn't use it either.

WM: Drop Meta.ShadowFactory

---

data/gala.appdata.xml.in
data/gala.css
src/Widgets/WindowSwitcher.vala

Resolves #1355
This PR does 2 things:
- Increases border radius of the shadow
- Cleans the canvas before drawing background

WindowSwitcher: Fix rounded corners

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala

WindowSwitcher: Update caption width before opening

---

src/Widgets/MultitaskingView.vala

MultitaskingView: Stack docks on top of workspace clones

---

src/Background/BackgroundManager.vala

Makes bright wallpapers actually dark :)

BackgroundManager: dark dim effect

---

src/Widgets/IconGroup.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WorkspaceClone.vala

* Animate icon group highlights with gestures
* Run animation as soon as the gesture stops, not when the workspace is actually switched.

IconGroup: Improve animation

---

src/Widgets/MultitaskingView.vala

I missed this in #1653 :sweat_smile:

Handle cancel action in IconGroup animation

---

src/WindowManager.vala

Window Dim: Use `get_transient_for`

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala

Resolves #124 
Allows using Left/Right arrow keys to navigate through windows and Enter key to select currently selected window.

WindowSwitcher: Improve keyboard navigation

---

data/gala.appdata.xml.in
meson.build

Anything else to squeeze in before release?

Release 7.0.3

---

debian/control

Change these to the versions we support

deb-packaging: Bump mutter versions

---

data/gala.metainfo.xml.in
src/Widgets/WindowSwitcher/WindowSwitcher.vala

Fixes #1706
Review with "Hide whitespace"

WindowSwitcher: Remove dark style css_provider if theme changes

---

data/gala.metainfo.xml.in
meson.build

Hotfix for https://github.com/elementary/gala/issues/1706 and https://github.com/elementary/gala/issues/1712.

Release 7.1.1

---

src/WindowManager.vala

Fix moving maximized and fullscreen windows to new workspace on launch

---

data/gala.css
src/WindowManager.vala

Add shadow to wallpaper clones while switching workspace

---

src/Widgets/MultitaskingView.vala
src/WindowManager.vala

Kill workspace switch when opening multitasking view

---

lib/Plugin.vala
src/PluginManager.vala

Remove `PluginFunction.DESKTOP`

---

data/gala.metainfo.xml.in
src/Background/Background.vala
src/Background/BackgroundManager.vala
src/Background/BackgroundSource.vala

Fixes #1774
- Don't use custom hacky way to set dimmed wallpaper
- Handle every settings change in `BackgroundSource`

Background: Cleanup

---

data/gala.gschema.xml
src/WindowManager.vala

Closes https://github.com/elementary/gala/issues/1739
Fixes #1109

Add "Move to workspace" gesture

---

src/Widgets/Tooltip.vala

Redraw tooltip to avoid corner glitches

---

src/Widgets/IconGroup.vala

IconGroup: remove close button

---

data/gala.gschema.xml
src/Background/SystemBackground.vala

Review with hidden whitespace changes
While we're here:
- Inline namespace
- Update copyright header

Remove  `workspace-switcher-background` key

---

data/gala.gschema.xml
src/Widgets/WindowSwitcher/WindowSwitcher.vala
src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/1317
Fixes https://github.com/elementary/gala/issues/979

Add "Switch windows" gesture

---

src/Background/BackgroundManager.vala
src/Widgets/MonitorClone.vala
src/Widgets/WorkspaceClone.vala

Branch based on https://github.com/elementary/gala/pull/1808
This code seems to be unnecessary.

BackgroundManager: Don't position background actors

---

data/gala.css
src/Widgets/IconGroup.vala
src/Widgets/MultitaskingView.vala

Adds a brightness effect based on dark or light mode to add some extra contrast between the background and the workspace

Add brightness effect for contrast

---

src/Background/BackgroundManager.vala
src/Widgets/MonitorClone.vala
src/Widgets/WorkspaceClone.vala

Reverts elementary/gala#1809
Fixes #1813
This code is necessary after all :(

Revert "BackgroundManager: Don't position background actors"

---

src/NotificationStack.vala

Show notifications on the left in RTL languages

---

src/Widgets/MultitaskingView.vala
src/WindowManager.vala

Use event time instead of META_CURRENT_TIME

---

src/WindowManager.vala

~Haven't tested it yet but I guess it makes sense and GNOME Shell does the same~ I can confirm this fixes the drag and drop icons not appearing
Fixes #1818

wayland: Fix drag and drop icons

---

data/gala.gschema.xml

Fixes https://github.com/elementary/gala/issues/847

Fix move-to-workspace-last shortcut

---

src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/547

Play sound when cycle-workspaces shortcut fails

---

src/Widgets/MultitaskingView.vala

Currently on wayland the dock isn't animated out and in

MultitaskingView: Fix dock animation

---

src/ShellClients/PanelWindow.vala

Primary monitor might have changed so resetup barriers and reposition window.

PanelWindow: Reposition windows on monitor change

---

src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/1945

Manually set ui_group size

---

lib/ShadowEffect.vala

ShadowEffect: Avoid painting inside the actor

---

src/ShellClients/PanelWindow.vala

Fixes #1961 
I ran this branch for a few days now and it didn't crash (vs. at least once or twice a day on master). So let's hope this fixes it :)

PanelWindow: Fix possible segfault

---

src/Widgets/WindowClone.vala

Fixes https://github.com/elementary/gala/issues/1271

WindowClone: Fix memory leak in window spread

---

debian/control

Goes with #1987
Also update the maintainer to elementary, Inc. while I'm here

control: Require meson >= 0.59.0

---

src/DBus.vala

* Inline namespace
* Remove methods that were moved into the wingpanel plugin 9 years ago

DBus: cleanup

---

src/Background/BackgroundManager.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WorkspaceClone.vala

Fixes the same issue as https://github.com/elementary/greeter/issues/737 but in multitasking view

Remove blurry rounded corners

---

src/WindowManager.vala

Fixes #2011 
Closes #2016 
Does pretty much the same as #2016 but also allows move via touchscreen.

Fix move/resize actions

---

data/gala.gschema.xml
src/WindowManager.vala

Addresses https://github.com/elementary/gala/issues/271

RDNN animations schema

---

debian/control

Required for https://github.com/elementary/gala/pull/2030

control: add libatk-bridge-2.0 dependency

---

src/WindowAttentionTracker.vala
src/WindowManager.vala
src/meson.build

Fixes https://github.com/elementary/gala/issues/1052

Focus window when it demands attention

---

src/ShellClients/PanelWindow.vala

Fixes elementary/wingpanel#540

PanelWindow: Fix struts not updating on scaling change

---

src/NotificationStack.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WindowOverview.vala
src/WindowManager.vala

Unifies a notification check to avoid mistakes and confusion in the future.

Unify notifications check

---

src/ShellClients/ManagedClient.vala

This way the output can be read via journalctl.

ManagedClient: Inherit fds

---

src/Widgets/WindowClone.vala

WindowClone: Only load after shown

---

src/ScreenshotManager.vala

ScreenshotManager: Fix cursor inclusion for non window screenshots

---

lib/DragDropAction.vala

Fixes https://github.com/elementary/gala/issues/2064

DragDropAction: properly handle button release event

---

src/WindowManager.vala

Fixes https://github.com/elementary/gala/issues/1967
Fixes https://github.com/elementary/gala/issues/2113
Fixes https://github.com/elementary/gala/issues/2131

Wayland: start gnome-session-x11-services-ready.target

---

src/ShellClients/PanelWindow.vala

ShellClients: Fix infinite loop on hide mode NEVER

---

data/gala.metainfo.xml.in
meson.build
src/ScreenshotManager.vala

There were a bunch of nice fixes recently, most notably #2160 which also fixed some crashes that have been around for a while (#2200) as well as some that aren't merged yet that I'd like to release before some more major changes (like #2204, #2195, #2096, and more gesture changes).
In theory there are new features (#2125 and #2164) so i'm not sure whether this should already be a 8.1.0?
Fixes #2200
Waiting for:

Release 8.1.0

---

src/WorkspaceManager.vala

Inline namespace and always use braces. Review with hide whitespaces.
Can be rebase merged if preferred.

WorkspaceManager: Code style

---

src/InternalUtils.vala
src/Widgets/IconGroup.vala
src/Widgets/MultitaskingView.vala
src/Widgets/WindowClone.vala
src/Widgets/WorkspaceInsertThumb.vala
src/WindowManager.vala
src/WorkspaceManager.vala

We don't support it in new code at all so it doesn't really makes sense to keep all of this code that works only half of the time.

Drop support for static workspaces

---

src/Widgets/MultitaskingView/MultitaskingView.vala
src/Widgets/MultitaskingView/WorkspaceClone.vala

No big changes for multitaskingview are currently pending so we can do this without having to do an annoying rebase :)
Review with hide whitespaces.

Inline namespace for MultitaskingView

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala

WindowSwitcher: adjust opacity and blur values

---

src/Widgets/WindowSwitcher/WindowSwitcher.vala

Fixes https://github.com/elementary/gala/issues/2308
Not sure if this will fix the issue but worth a try I guess

WindowSwitcher: use Clutter.Stage.set_key_focus ()

---

src/Widgets/MultitaskingView/WindowClone.vala

Fixes https://github.com/elementary/gala/issues/1235

WindowClone: always show window title

---

src/ShellClients/PositionedWindow.vala

Fixes https://github.com/elementary/gala/issues/2294
Fixes https://github.com/elementary/gala/issues/2341

PositionedWindow: block position_changed signal while positioning

---

debian/postinst

Make sure we migrate multitasking view shortcut to a new key

Migrate multitasking view shortcut

---

data/gala.metainfo.xml.in
meson.build

Release 8.2.0

---

.gitignore
data/gala.metainfo.xml.in
src/Widgets/MultitaskingView/MultitaskingView.vala

Fixes https://github.com/elementary/gala/issues/2322

Fix workspace switch

---

meson.build

Hotfix for https://github.com/elementary/gala/issues/2322 and https://github.com/elementary/gala/pull/2391

Release 8.2.1

---

data/gala.metainfo.xml.in
src/Widgets/MultitaskingView/MultitaskingView.vala

Fixes https://github.com/elementary/gala/issues/2387
I don't have second monitor to test but I suppose this should fix it

MultitaskingView: Always show monitor clones

---

data/gala.metainfo.xml.in
meson.build

Release 8.2.2

---

data/gala.metainfo.xml.in
src/Widgets/MultitaskingView/WindowClone.vala

Fixes https://github.com/elementary/gala/issues/2400

WindowClone: Fix interaction with multiple monitors

---

src/Widgets/MultitaskingView/WindowCloneContainer.vala
src/Widgets/WindowOverview.vala

Fixes https://github.com/elementary/gala/issues/132

Close window overview when last window is closed

---

meson.build

Release 8.2.3

---

data/gala.metainfo.xml.in
src/WindowStateSaver.vala

Fixes https://github.com/elementary/gala/issues/2438

WindowStateSaver: fix crash

---

data/gala.metainfo.xml.in
meson.build

Release 8.2.4

---

src/Widgets/MultitaskingView/WindowClone.vala

Fixes https://github.com/elementary/gala/issues/2445

WindowClone: update targets on minimize

---

.github/workflows/main.yml
README.md

It was added in https://github.com/elementary/gala/pull/36. But I don't think we need this anymore

Remove libxml2 dependency

---

daemon-gtk3/DBus.vala

Fixes https://github.com/elementary/gala/issues/2454

Fix gtk3 daemon menu location with x2 scaling

---

lib/Gestures/GestureBackend.vala
lib/Gestures/GestureController.vala
lib/Gestures/ScrollBackend.vala
lib/Gestures/ToucheggBackend.vala
lib/Gestures/TouchpadBackend.vala
src/Widgets/MultitaskingView/MultitaskingView.vala

Fixes https://github.com/elementary/gala/issues/2399

Make workspace switch gesture follow natural scrolling setting

---

src/BackgroundBlurEffect.vala

Fixes crash with https://github.com/elementary/notifications/pull/251 when window width becomes 0 for some reason

BackgroundBlurEffect: Fix crash

---

src/NotificationStack.vala

You can test this animation with https://github.com/elementary/notifications/pull/252

Cleanup notification close animation
